In [64]:
import numpy as np 
import pandas as pd

In [65]:
movies = pd.read_csv('tmdb_5000_movies.csv.zip')
credits = pd.read_csv('tmdb_5000_credits.csv.zip')

In [67]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [68]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [70]:
movies.merge(credits,on='title').shape

(4809, 23)

In [71]:
movies.shape

(4803, 20)

In [72]:
credits.shape

(4803, 4)

In [73]:
movies = movies.merge(credits,on='title')

In [74]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [75]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [76]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [77]:
movies[['movie_id','title','overview','genres','keywords','cast','crew']]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [78]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [79]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [80]:
movies.dropna(inplace=True)

In [81]:
movies.duplicated().sum()

np.int64(0)

In [82]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [96]:
def convert(obj):
    
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
             L.append(i['name'])
             counter += 1
        else:
            break
       
    return L

In [88]:
import ast

ast.literal_eval(
    '[{"id":28, "name":"Action"}, {"id":14, "name":"Fantasy"}, {"id":878, "name":"Science Fiction"}]'
)

[{'id': 28, 'name': 'Action'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [91]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4779                                         [Comedy]
4787                                [Comedy, Romance]
4797                                         [Horror]
4802               [Science Fiction, Drama, Thriller]
4807                                               []
Name: genres, Length: 1494, dtype: object

In [92]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [93]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4779             [salesclerk, loser, aftercreditsstinger]
4787    [dating, divorce, sex scene, sex comedy, anti ...
4797                                      [home invasion]
4802    [distrust, garage, identity crisis, time trave...
4807                                                   []
Name: keywords, Length: 1494, dtype: object

In [95]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [97]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4779       [Brian O'Halloran, Jeff Anderson, Jason Mewes]
4787         [Suzi Lorraine, Jared Degado, Heather Dorff]
4797    [Michael Parle, Emma Eliza Regan, Patrick O'Do...
4802        [Shane Carruth, David Sullivan, Casey Gooden]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
Name: cast, Length: 1494, dtype: object

In [98]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [99]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [100]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
        return L

In [101]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [102]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[]
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[]
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[]
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[]
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[]

In [103]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [105]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4779    [Convenience, and, video, store, clerks, Dante...
4787    [Sasha, tries, to, get, her, soon-to-be, ex, h...
4797    [Recently, dumped, by, his, girlfirend, for, a...
4802    [Friends/fledgling, entrepreneurs, invent, a, ...
4807    [When, ambitious, New, York, attorney, Sam, is...
Name: overview, Length: 1494, dtype: object

In [106]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[]
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[]
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[]
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[]
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[]

In [107]:
movies["genres"] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies["keywords"] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies["cast"] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies["crew"] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

TypeError: 'NoneType' object is not iterable

In [108]:
movies['crew'].head()

0    []
1    []
2    []
3    []
4    []
Name: crew, dtype: object

In [109]:
movies['crew'].apply(type).value_counts()

crew
<class 'list'>        1266
<class 'NoneType'>     228
Name: count, dtype: int64

In [110]:
movies[movies['crew'].apply(lambda x: x is None)]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
13,255000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://disney.go.com/the-lone-ranger/,57201,"[[, {, "", i, d, "", :, , 1, 5, 5, 6, ,, , "", n,...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311,57201,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",None
40,200000000,"[[, {, "", i, d, "", :, , 1, 6, ,, , "", n, a, m,...",http://www.disney.go.com/cars/,49013,"[[, {, "", i, d, "", :, , 8, 3, 0, ,, , "", n, a,...",en,Cars 2,Star race car Lightning McQueen and his pal Ma...,49.986590,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Ka-ciao!,Cars 2,5.8,2033,49013,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",None
44,190000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.furious7.com/,168259,"[[, {, "", i, d, "", :, , 8, 3, 0, ,, , "", n, a,...",en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,102.322217,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,137.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Vengeance Hits Home,Furious 7,7.3,4176,168259,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, 7, ,...",None
51,180000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.pacificrimmovie.com/,68726,"[[, {, "", i, d, "", :, , 4, 5, 6, 5, ,, , "", n,...",en,Pacific Rim,"When legions of monstrous creatures, known as ...",56.523205,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,131.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"To Fight Monsters, We Created Monsters",Pacific Rim,6.7,4794,68726,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",None
67,175000000,"[[, {, "", i, d, "", :, , 1, 6, ,, , "", n, a, m,...",http://www.monstersvsaliens.com/,15512,"[[, {, "", i, d, "", :, , 9, 9, 5, 1, ,, , "", n,...",en,Monsters vs Aliens,When Susan Murphy is unwittingly clobbered by ...,36.167578,"[{""name"": ""DreamWorks Animation"", ""id"": 521}]",...,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"When aliens attack, monsters fight back.",Monsters vs Aliens,6.0,1423,15512,"[[, {, "", c, a, s, t, _, i, d, "", :, , 8, ,, ,...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4779,27000,"[[, {, "", i, d, "", :, , 3, 5, ,, , "", n, a, m,...",http://www.miramax.com/movie/clerks/,2292,"[[, {, "", i, d, "", :, , 1, 3, 6, 1, ,, , "", n,...",en,Clerks,Convenience and video store clerks Dante and R...,19.748658,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just because they serve you doesn't mean they ...,Clerks,7.4,755,2292,"[[, {, "", c, a, s, t, _, i, d, "", :, , 7, ,, ,...",None
4787,22000,"[[, {, "", i, d, "", :, , 3, 5, ,, , "", n, a, m,...",https://www.facebook.com/DrySpellMovie,255266,"[[, {, "", i, d, "", :, , 1, 3, 0, 4, 3, ,, , "",...",en,Dry Spell,Sasha tries to get her soon-to-be ex husband K...,0.048948,[],...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Getting divorced does funny things to a girl,Dry Spell,6.0,1,255266,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",None
4797,13,"[[, {, "", i, d, "", :, , 2, 7, ,, , "", n, a, m,...",http://tincanmanthemovie.com/,157185,"[[, {, "", i, d, "", :, , 1, 4, 9, 0, 3, ,, , "",...",en,Tin Can Man,Recently dumped by his girlfirend for another ...,0.332679,"[{""name"": ""Park Films"", ""id"": 21871}, {""name"":...",...,84.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Everything You've Heard is True,Tin Can Man,2.0,1,157185,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",None
4802,7000,"[[, {, "", i, d, "", :, , 8, 7, 8, ,, , "", n, a,...",http://www.primermovie.com,14337,"[[, {, "", i, d, "", :, , 1, 4, 4, 8, ,, , "", n,...",en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]",...,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens if it actually works?,Primer,6.9,658,14337,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",None
4807,0,"[[, ]]",http://shanghaicalling.com/,126186,"[[, ]]",en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[[, {, "", c, a, s, t, _, i, d, "", :, , 3, ,, ,...",None

In [111]:
import ast

def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [112]:
movies['crew'] = movies['crew'].apply(fetch_director)

ValueError: malformed node or string: []

In [113]:
print(type(movies['crew'].iloc[0]))
print(movies['crew'].iloc[0])

<class 'list'>
[]

In [114]:
movies["genres"] = movies["genres"].apply(lambda x: [i.replace(" ", "") for i in x])
movies["keywords"] = movies["keywords"].apply(lambda x: [i.replace(" ", "") for i in x])
movies["cast"] = movies["cast"].apply(lambda x: [i.replace(" ", "") for i in x])
movies["crew"] = movies["crew"].apply(lambda x: [i.replace(" ", "") for i in x])

TypeError: 'NoneType' object is not iterable

In [115]:
movies["crew"].apply(type).value_counts()

crew
<class 'list'>        1266
<class 'NoneType'>     228
Name: count, dtype: int64

In [116]:
movies["crew"] = movies["crew"].apply(
    lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else []
)

In [117]:
movies["crew"] = movies["crew"].apply(
    lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else []
)

In [118]:
# 1. Tags column banao
movies['tags'] = (
    movies['overview'] +
    movies['genres'] +
    movies['keywords'] +
    movies['cast'] +
    movies['crew']
)

TypeError: can only concatenate str (not "list") to str

In [119]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [120]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [121]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew,tags
0,237000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.avatarmovie.com/,19995,"[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...",en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,300000000,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...",http://disney.go.com/disneypictures/pirates/,285,"[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...",en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[],"[Captain, Barbossa,, long, believed, to, be, d..."
2,245000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.sonypictures.com/movies/spectre/,206647,"[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...",en,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[],"[A, cryptic, message, from, Bond’s, past, send..."
3,250000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://www.thedarkknightrises.com/,49026,"[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...",en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[],"[Following, the, death, of, District, Attorney..."
4,260000000,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",http://movies.disney.com/john-carter,49529,"[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...",en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[],"[John, Carter, is, a, war-weary,, former, mili..."

In [122]:
new_df = movies[['movie_id', 'title', 'tags']]

In [124]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_29660\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [125]:
new_df = movies[['movie_id', 'title', 'tags']].copy()

In [126]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [127]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [128]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [129]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e "

In [130]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [131]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e "

In [132]:
genres = ['Action', 'Adventure', 'Fantasy']
keywords = ['future', 'space']
cast = ['SamWorthington', 'ZoeSaldana']
crew = ['JamesCameron']

In [133]:
tags = overview + genres + keywords + cast + crew

NameError: name 'overview' is not defined

In [134]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [136]:
tags =  genres + keywords + cast + crew

In [137]:
new_df['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e "

In [138]:
from sklearn.feature_extraction.text import ConterVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

ImportError: cannot import name 'ConterVectorizer' from 'sklearn.feature_extraction.text' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py)

In [144]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [145]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [146]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [148]:
len(cv.get_feature_names_out())

5000

In [149]:
['loved','loving','love']
['love','love','love']

['love', 'love', 'love']

In [150]:
import nltk

In [151]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [155]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [153]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e "

In [154]:
ps.stem('loved')

'love'

In [156]:
stem(''in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e " :  " m a t t  c l a y t o n " ,  " o r d e r " :  6 2 } ,  { " c a s t _ i d " :  8 4 ,  " c h a r a c t e r " :  " n a v \' i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " ,  " g e n d e r " :  1 ,  " i d " :  1 4 7 8 9 8 ,  " n a m e " :  " n i c o l e  d i o n n e " ,  " o r d e r " :  6 3 } ,  { " c a s t _ i d " :  8 5 ,  " c h a r a c t e r " :  " t r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 0 ,  " n a m e " :  " j a m i e  h a r r i s o n " ,  " o r d e r " :  6 4 } ,  { " c a s t _ i d " :  8 6 ,  " c h a r a c t e r " :  " t r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 1 ,  " n a m e " :  " a l l a n  h e n r y " ,  " o r d e r " :  6 5 } ,  { " c a s t _ i d " :  8 7 ,  " c h a r a c t e r " :  " g r o u n d  t e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 2 0 7 2 8 2 ,  " n a m e " :  " a n t h o n y  i n g r u b e r " ,  " o r d e r " :  6 6 } ,  { " c a s t _ i d " :  8 8 ,  " c h a r a c t e r " :  " f l i g h t  c r e w  m e c h a n i c  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 3 ,  " n a m e " :  " a s h l e y  j e f f e r y " ,  " o r d e r " :  6 7 } ,  { " c a s t _ i d " :  1 4 ,  " c h a r a c t e r " :  " s a m s o n  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 9 " ,  " g e n d e r " :  0 ,  " i d " :  9 8 2 1 6 ,  " n a m e " :  " d e a n  k n o w s l e y " ,  " o r d e r " :  6 8 } ,  { " c a s t _ i d " :  8 9 ,  " c h a r a c t e r " :  " t r o o p e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 1 3 9 9 ,  " n a m e " :  " j o s e p h  m i k a - h u n t " ,  " o r d e r " :  6 9 } ,  { " c a s t _ i d " :  9 0 ,  " c h a r a c t e r " :  " b a n s h e e  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 f " ,  " g e n d e r " :  0 ,  " i d " :  2 3 6 6 9 6 ,  " n a m e " :  " t e r r y  n o t a r y " ,  " o r d e r " :  7 0 } ,  { " c a s t _ i d " :  9 1 ,  " c h a r a c t e r " :  " s o l d i e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 7 ,  " n a m e " :  " k a i  p a n t a n o " ,  " o r d e r " :  7 1 } ,  { " c a s t _ i d " :  9 2 ,  " c h a r a c t e r " :  " b l a s t  t e c h n i c i a n  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 8 ,  " n a m e " :  " l o g a n  p i t h y o u " ,  " o r d e r " :  7 2 } ,  { " c a s t _ i d " :  9 3 ,  " c h a r a c t e r " :  " v i n d u m  r a a h  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 8 9 ,  " n a m e " :  " s t u a r t  p o l l o c k " ,  " o r d e r " :  7 3 } ,  { " c a s t _ i d " :  9 4 ,  " c h a r a c t e r " :  " h e r o  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 4 f " ,  " g e n d e r " :  0 ,  " i d " :  5 8 4 8 6 8 ,  " n a m e " :  " r a j a " ,  " o r d e r " :  7 4 } ,  { " c a s t _ i d " :  9 5 ,  " c h a r a c t e r " :  " o p s  c e n t r e w o r k e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 9 0 ,  " n a m e " :  " g a r e t h  r u c k " ,  " o r d e r " :  7 5 } ,  { " c a s t _ i d " :  9 6 ,  " c h a r a c t e r " :  " e n g i n e e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 0 6 2 4 6 3 ,  " n a m e " :  " r h i a n  s h e e h a n " ,  " o r d e r " :  7 6 } ,  { " c a s t _ i d " :  9 7 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h \' s  m e c h  s u i t  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 b " ,  " g e n d e r " :  0 ,  " i d " :  6 0 6 5 6 ,  " n a m e " :  " t .  j .  s t o r m " ,  " o r d e r " :  7 7 } ,  { " c a s t _ i d " :  9 8 ,  " c h a r a c t e r " :  " f e m a l e  m a r i n e  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 5 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 9 1 ,  " n a m e " :  " j o d i e  t a y l o r " ,  " o r d e r " :  7 8 } ,  { " c a s t _ i d " :  9 9 ,  " c h a r a c t e r " :  " i k r a n  c l a n  l e a d e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 1 8 6 0 2 7 ,  " n a m e " :  " a l i c i a  v e l a - b a i l e y " ,  " o r d e r " :  7 9 } ,  { " c a s t _ i d " :  1 0 0 ,  " c h a r a c t e r " :  " g e o l o g i s t  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 9 2 ,  " n a m e " :  " r i c h a r d  w h i t e s i d e " ,  " o r d e r " :  8 0 } ,  { " c a s t _ i d " :  1 0 1 ,  " c h a r a c t e r " :  " n a \' v i  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 0 3 2 5 9 ,  " n a m e " :  " n i k i e  z a m b o " ,  " o r d e r " :  8 1 } ,  { " c a s t _ i d " :  1 0 2 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 6 f " ,  " g e n d e r " :  1 ,  " i d " :  4 2 2 8 6 ,  " n a m e " :  " j u l e n e  r e n e e " ,  " o r d e r " :  8 2 } ]'')

SyntaxError: invalid decimal literal (3133439463.py, line 1)

In [157]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] [ { " c a s t _ i d " :  2 4 2 ,  " c h a r a c t e r " :  " j a k e  s u l l y " ,  " c r e d i t _ i d " :  " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " ,  " g e n d e r " :  2 ,  " i d " :  6 5 7 3 1 ,  " n a m e " :  " s a m  w o r t h i n g t o n " ,  " o r d e r " :  0 } ,  { " c a s t _ i d " :  3 ,  " c h a r a c t e r " :  " n e y t i r i " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " ,  " g e n d e r " :  1 ,  " i d " :  8 6 9 1 ,  " n a m e " :  " z o e  s a l d a n a " ,  " o r d e r " :  1 } ,  { " c a s t _ i d " :  2 5 ,  " c h a r a c t e r " :  " d r .  g r a c e  a u g u s t i n e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " ,  " g e n d e r " :  1 ,  " i d " :  1 0 2 0 5 ,  " n a m e " :  " s i g o u r n e y  w e a v e r " ,  " o r d e r " :  2 } ,  { " c a s t _ i d " :  4 ,  " c h a r a c t e r " :  " c o l .  q u a r i t c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " ,  " g e n d e r " :  2 ,  " i d " :  3 2 7 4 7 ,  " n a m e " :  " s t e p h e n  l a n g " ,  " o r d e r " :  3 } ,  { " c a s t _ i d " :  5 ,  " c h a r a c t e r " :  " t r u d y  c h a c o n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " ,  " g e n d e r " :  1 ,  " i d " :  1 7 6 4 7 ,  " n a m e " :  " m i c h e l l e  r o d r i g u e z " ,  " o r d e r " :  4 } ,  { " c a s t _ i d " :  8 ,  " c h a r a c t e r " :  " s e l f r i d g e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " ,  " g e n d e r " :  2 ,  " i d " :  1 7 7 1 ,  " n a m e " :  " g i o v a n n i  r i b i s i " ,  " o r d e r " :  5 } ,  { " c a s t _ i d " :  7 ,  " c h a r a c t e r " :  " n o r m  s p e l l m a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " ,  " g e n d e r " :  2 ,  " i d " :  5 9 2 3 1 ,  " n a m e " :  " j o e l  d a v i d  m o o r e " ,  " o r d e r " :  6 } ,  { " c a s t _ i d " :  9 ,  " c h a r a c t e r " :  " m o a t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " ,  " g e n d e r " :  1 ,  " i d " :  3 0 4 8 5 ,  " n a m e " :  " c c h  p o u n d e r " ,  " o r d e r " :  7 } ,  { " c a s t _ i d " :  1 1 ,  " c h a r a c t e r " :  " e y t u k a n " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " ,  " g e n d e r " :  2 ,  " i d " :  1 5 8 5 3 ,  " n a m e " :  " w e s  s t u d i " ,  " o r d e r " :  8 } ,  { " c a s t _ i d " :  1 0 ,  " c h a r a c t e r " :  " t s u \' t e y " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 9 6 4 ,  " n a m e " :  " l a z  a l o n s o " ,  " o r d e r " :  9 } ,  { " c a s t _ i d " :  1 2 ,  " c h a r a c t e r " :  " d r .  m a x  p a t e l " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " ,  " g e n d e r " :  2 ,  " i d " :  9 5 6 9 7 ,  " n a m e " :  " d i l e e p  r a o " ,  " o r d e r " :  1 0 } ,  { " c a s t _ i d " :  1 3 ,  " c h a r a c t e r " :  " l y l e  w a i n f l e e t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 2 1 5 ,  " n a m e " :  " m a t t  g e r a l d " ,  " o r d e r " :  1 1 } ,  { " c a s t _ i d " :  3 2 ,  " c h a r a c t e r " :  " p r i v a t e  f i k e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " ,  " g e n d e r " :  2 ,  " i d " :  1 5 4 1 5 3 ,  " n a m e " :  " s e a n  a n t h o n y  m o r a n " ,  " o r d e r " :  1 2 } ,  { " c a s t _ i d " :  3 3 ,  " c h a r a c t e r " :  " c r y o  v a u l t  m e d  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " ,  " g e n d e r " :  2 ,  " i d " :  3 9 7 3 1 2 ,  " n a m e " :  " j a s o n  w h y t e " ,  " o r d e r " :  1 3 } ,  { " c a s t _ i d " :  3 4 ,  " c h a r a c t e r " :  " v e n t u r e  s t a r  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " ,  " g e n d e r " :  2 ,  " i d " :  4 2 3 1 7 ,  " n a m e " :  " s c o t t  l a w r e n c e " ,  " o r d e r " :  1 4 } ,  { " c a s t _ i d " :  3 5 ,  " c h a r a c t e r " :  " l o c k  u p  t r o o p e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " ,  " g e n d e r " :  2 ,  " i d " :  9 8 6 7 3 4 ,  " n a m e " :  " k e l l y  k i l g o u r " ,  " o r d e r " :  1 5 } ,  { " c a s t _ i d " :  3 6 ,  " c h a r a c t e r " :  " s h u t t l e  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 2 7 ,  " n a m e " :  " j a m e s  p a t r i c k  p i t t " ,  " o r d e r " :  1 6 } ,  { " c a s t _ i d " :  3 7 ,  " c h a r a c t e r " :  " s h u t t l e  c o - p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " ,  " g e n d e r " :  0 ,  " i d " :  1 1 8 0 9 3 6 ,  " n a m e " :  " s e a n  p a t r i c k  m u r p h y " ,  " o r d e r " :  1 7 } ,  { " c a s t _ i d " :  3 8 ,  " c h a r a c t e r " :  " s h u t t l e  c r e w  c h i e f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " ,  " g e n d e r " :  2 ,  " i d " :  1 0 1 9 5 7 8 ,  " n a m e " :  " p e t e r  d i l l o n " ,  " o r d e r " :  1 8 } ,  { " c a s t _ i d " :  3 9 ,  " c h a r a c t e r " :  " t r a c t o r  o p e r a t o r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " ,  " g e n d e r " :  0 ,  " i d " :  9 1 4 4 3 ,  " n a m e " :  " k e v i n  d o r m a n " ,  " o r d e r " :  1 9 } ,  { " c a s t _ i d " :  4 0 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  p i l o t " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " ,  " g e n d e r " :  2 ,  " i d " :  1 7 3 3 9 1 ,  " n a m e " :  " k e l s o n  h e n d e r s o n " ,  " o r d e r " :  2 0 } ,  { " c a s t _ i d " :  4 1 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  g u n n e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 3 6 ,  " n a m e " :  " d a v i d  v a n  h o r n " ,  " o r d e r " :  2 1 } ,  { " c a s t _ i d " :  4 2 ,  " c h a r a c t e r " :  " d r a g o n  g u n s h i p  n a v i g a t o r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " ,  " g e n d e r " :  0 ,  " i d " :  2 1 5 9 1 3 ,  " n a m e " :  " j a c o b  t o m u r i " ,  " o r d e r " :  2 2 } ,  { " c a s t _ i d " :  4 3 ,  " c h a r a c t e r " :  " s u i t  # 1 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 4 3 2 0 6 ,  " n a m e " :  " m i c h a e l  b l a i n - r o z g a y " ,  " o r d e r " :  2 3 } ,  { " c a s t _ i d " :  4 4 ,  " c h a r a c t e r " :  " s u i t  # 2 " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " ,  " g e n d e r " :  2 ,  " i d " :  1 6 9 6 7 6 ,  " n a m e " :  " j o n  c u r r y " ,  " o r d e r " :  2 4 } ,  { " c a s t _ i d " :  4 6 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 4 8 6 1 0 ,  " n a m e " :  " l u k e  h a w k e r " ,  " o r d e r " :  2 5 } ,  { " c a s t _ i d " :  4 7 ,  " c h a r a c t e r " :  " a m b i e n t  r o o m  t e c h  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " ,  " g e n d e r " :  0 ,  " i d " :  4 2 2 8 8 ,  " n a m e " :  " w o o d y  s c h u l t z " ,  " o r d e r " :  2 6 } ,  { " c a s t _ i d " :  4 8 ,  " c h a r a c t e r " :  " h o r s e  c l a n  l e a d e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " ,  " g e n d e r " :  2 ,  " i d " :  6 8 2 7 8 ,  " n a m e " :  " p e t e r  m e n s a h " ,  " o r d e r " :  2 7 } ,  { " c a s t _ i d " :  4 9 ,  " c h a r a c t e r " :  " l i n k  r o o m  t e c h " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 7 ,  " n a m e " :  " s o n i a  y e e " ,  " o r d e r " :  2 8 } ,  { " c a s t _ i d " :  5 0 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r  /  t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " ,  " g e n d e r " :  1 ,  " i d " :  1 2 0 7 2 4 8 ,  " n a m e " :  " j a h n e l  c u r f m a n " ,  " o r d e r " :  2 9 } ,  { " c a s t _ i d " :  5 1 ,  " c h a r a c t e r " :  " b a s k e t b a l l  a v a t a r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " ,  " g e n d e r " :  0 ,  " i d " :  8 9 7 1 4 ,  " n a m e " :  " i l r a m  c h o i " ,  " o r d e r " :  3 0 } ,  { " c a s t _ i d " :  5 2 ,  " c h a r a c t e r " :  " n a \' v i  c h i l d " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 4 9 ,  " n a m e " :  " k y l a  w a r r e n " ,  " o r d e r " :  3 1 } ,  { " c a s t _ i d " :  5 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 0 ,  " n a m e " :  " l i s a  r o u m a i n " ,  " o r d e r " :  3 2 } ,  { " c a s t _ i d " :  5 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " ,  " g e n d e r " :  1 ,  " i d " :  8 3 1 0 5 ,  " n a m e " :  " d e b r a  w i l s o n " ,  " o r d e r " :  3 3 } ,  { " c a s t _ i d " :  5 7 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 3 ,  " n a m e " :  " c h r i s  m a l a " ,  " o r d e r " :  3 4 } ,  { " c a s t _ i d " :  5 5 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 1 ,  " n a m e " :  " t a y l o r  k i b b y " ,  " o r d e r " :  3 5 } ,  { " c a s t _ i d " :  5 6 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 2 ,  " n a m e " :  " j o d i e  l a n d a u " ,  " o r d e r " :  3 6 } ,  { " c a s t _ i d " :  5 8 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 4 ,  " n a m e " :  " j u l i e  l a m m " ,  " o r d e r " :  3 7 } ,  { " c a s t _ i d " :  5 9 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 7 ,  " n a m e " :  " c u l l e n  b .  m a d d e n " ,  " o r d e r " :  3 8 } ,  { " c a s t _ i d " :  6 0 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 5 9 ,  " n a m e " :  " j o s e p h  b r a d y  m a d d e n " ,  " o r d e r " :  3 9 } ,  { " c a s t _ i d " :  6 1 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 2 ,  " n a m e " :  " f r a n k i e  t o r r e s " ,  " o r d e r " :  4 0 } ,  { " c a s t _ i d " :  6 2 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " ,  " g e n d e r " :  1 ,  " i d " :  1 1 5 8 6 0 0 ,  " n a m e " :  " a u s t i n  w i l s o n " ,  " o r d e r " :  4 1 } ,  { " c a s t _ i d " :  6 3 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " ,  " g e n d e r " :  1 ,  " i d " :  9 8 3 7 0 5 ,  " n a m e " :  " s a r a  w i l s o n " ,  " o r d e r " :  4 2 } ,  { " c a s t _ i d " :  6 4 ,  " c h a r a c t e r " :  " t r o u p e " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 3 ,  " n a m e " :  " t a m i c a  w a s h i n g t o n - m i l l e r " ,  " o r d e r " :  4 3 } ,  { " c a s t _ i d " :  6 5 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " ,  " g e n d e r " :  1 ,  " i d " :  1 1 4 5 0 9 8 ,  " n a m e " :  " l u c y  b r i a n t " ,  " o r d e r " :  4 4 } ,  { " c a s t _ i d " :  6 6 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 0 5 ,  " n a m e " :  " n a t h a n  m e i s t e r " ,  " o r d e r " :  4 5 } ,  { " c a s t _ i d " :  6 7 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 4 ,  " n a m e " :  " g e r r y  b l a i r " ,  " o r d e r " :  4 6 } ,  { " c a s t _ i d " :  6 8 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " ,  " g e n d e r " :  2 ,  " i d " :  3 3 3 1 1 ,  " n a m e " :  " m a t t h e w  c h a m b e r l a i n " ,  " o r d e r " :  4 7 } ,  { " c a s t _ i d " :  6 9 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 5 ,  " n a m e " :  " p a u l  y a t e s " ,  " o r d e r " :  4 8 } ,  { " c a s t _ i d " :  7 0 ,  " c h a r a c t e r " :  " o p  c e n t e r  d u t y  o f f i c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 6 ,  " n a m e " :  " w r a y  w i l s o n " ,  " o r d e r " :  4 9 } ,  { " c a s t _ i d " :  7 1 ,  " c h a r a c t e r " :  " o p  c e n t e r  s t a f f " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " ,  " g e n d e r " :  2 ,  " i d " :  5 4 4 9 2 ,  " n a m e " :  " j a m e s  g a y l y n " ,  " o r d e r " :  5 0 } ,  { " c a s t _ i d " :  7 2 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 7 ,  " n a m e " :  " m e l v i n  l e n o  c l a r k  i i i " ,  " o r d e r " :  5 1 } ,  { " c a s t _ i d " :  7 3 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 8 ,  " n a m e " :  " c a r v o n  f u t r e l l " ,  " o r d e r " :  5 2 } ,  { " c a s t _ i d " :  7 4 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 6 9 ,  " n a m e " :  " b r a n d o n  j e l k e s " ,  " o r d e r " :  5 3 } ,  { " c a s t _ i d " :  7 5 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 0 ,  " n a m e " :  " m i c a h  m o c h " ,  " o r d e r " :  5 4 } ,  { " c a s t _ i d " :  7 6 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 1 ,  " n a m e " :  " h a n n i y a h  m u h a m m a d " ,  " o r d e r " :  5 5 } ,  { " c a s t _ i d " :  7 7 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 2 ,  " n a m e " :  " c h r i s t o p h e r  n o l e n " ,  " o r d e r " :  5 6 } ,  { " c a s t _ i d " :  7 8 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 3 ,  " n a m e " :  " c h r i s t a  o l i v e r " ,  " o r d e r " :  5 7 } ,  { " c a s t _ i d " :  7 9 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 4 ,  " n a m e " :  " a p r i l  m a r i e  t h o m a s " ,  " o r d e r " :  5 8 } ,  { " c a s t _ i d " :  8 0 ,  " c h a r a c t e r " :  " d a n c e r " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 5 ,  " n a m e " :  " b r a v i t a  a .  t h r e a t t " ,  " o r d e r " :  5 9 } ,  { " c a s t _ i d " :  8 1 ,  " c h a r a c t e r " :  " m i n i n g  c h i e f  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 6 ,  " n a m e " :  " c o l i n  b l e a s d a l e " ,  " o r d e r " :  6 0 } ,  { " c a s t _ i d " :  8 2 ,  " c h a r a c t e r " :  " v e t e r a n  m i n e r  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " ,  " g e n d e r " :  0 ,  " i d " :  1 0 7 9 6 9 ,  " n a m e " :  " m i k e  b o d n a r " ,  " o r d e r " :  6 1 } ,  { " c a s t _ i d " :  8 3 ,  " c h a r a c t e r " :  " r i c h a r d  ( u n c r e d i t e d ) " ,  " c r e d i t _ i d " :  " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " ,  " g e n d e r " :  0 ,  " i d " :  1 2 0 7 2 7 8 ,  " n a m e "

In [158]:
new_df['tags'] = new_df['tags'].apply(stem)

In [159]:
new_df['tags'][3000]

'a nanny, work for a famili whose son ha just pass away, find herself put in charg of care for a lifelik doll that the coupl treat as a real child. [ { " i d " : 2 7 , " n a m e " : " h o r r o r " } , { " i d " : 9 6 4 8 , " n a m e " : " m y s t e r y " } , { " i d " : 5 3 , " n a m e " : " t h r i l l e r " } ] [ { " i d " : 2 3 6 , " n a m e " : " s u i c i d e " } , { " i d " : 3 9 2 , " n a m e " : " e n g l a n d " } , { " i d " : 6 5 7 , " n a m e " : " f i r e " } , { " i d " : 1 6 5 5 , " n a m e " : " c o u n t r y h o u s e " } , { " i d " : 1 8 7 9 , " n a m e " : " s h o w e r " } , { " i d " : 2 3 4 1 , " n a m e " : " n a n n y " } , { " i d " : 2 5 4 6 , " n a m e " : " m a s k " } , { " i d " : 5 2 0 2 , " n a m e " : " b o y " } , { " i d " : 9 8 2 6 , " n a m e " : " m u r d e r " } , { " i d " : 1 2 5 4 5 , " n a m e " : " m a n s i o n " } , { " i d " : 1 4 8 1 9 , " n a m e " : " v i o l e n c e " } , { " i d " : 3 3 6 3 0 , " n a m e " : " d o l l " } , { " i d " : 1 5 8 5 6 7 , " n a m e " : " b u r n v i c t i m " } , { " i d " : 1 7 1 9 6 4 , " n a m e " : " s e c r e t p a s s a g e w a y " } , { " i d " : 1 7 6 7 0 6 , " n a m e " : " b r o k e n m i r r o r " } , { " i d " : 2 0 4 2 9 8 , " n a m e " : " l o s s o f a c h i l d " } ] [ { " c a s t _ i d " : 2 , " c h a r a c t e r " : " g r e t a e v a n s " , " c r e d i t _ i d " : " 5 5 1 8 6 f 6 0 9 2 5 1 4 1 6 f 0 a 0 0 4 a c 2 " , " g e n d e r " : 1 , " i d " : 6 2 2 2 0 , " n a m e " : " l a u r e n c o h a n " , " o r d e r " : 0 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " m a l c o l m " , " c r e d i t _ i d " : " 5 6 4 f c 8 b 3 9 2 5 1 4 1 6 4 c 0 0 0 1 5 d e " , " g e n d e r " : 2 , " i d " : 1 7 2 8 3 , " n a m e " : " r u p e r t e v a n s " , " o r d e r " : 1 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " b r a h m s h e e l s h i r e " , " c r e d i t _ i d " : " 5 5 1 8 6 f 6 8 9 2 5 1 4 1 2 c b 9 0 0 2 f 9 5 " , " g e n d e r " : 0 , " i d " : 1 0 2 9 4 0 3 , " n a m e " : " j a m e s r u s s e l l " , " o r d e r " : 2 } , { " c a s t _ i d " : 6 , " c h a r a c t e r " : " m r . h e e l s h i r e " , " c r e d i t _ i d " : " 5 6 4 f c 8 d d c 3 a 3 6 8 0 7 1 6 0 0 5 a 1 8 " , " g e n d e r " : 2 , " i d " : 1 4 9 5 0 , " n a m e " : " j i m n o r t o n " , " o r d e r " : 3 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " m r s . h e e l s h i r e " , " c r e d i t _ i d " : " 5 6 4 f c 8 f 2 9 2 5 1 4 1 4 a f 5 0 0 5 7 5 0 " , " g e n d e r " : 1 , " i d " : 3 4 6 3 5 2 , " n a m e " : " d i a n a h a r d c a s t l e " , " o r d e r " : 4 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " c o l e " , " c r e d i t _ i d " : " 5 6 4 f c 8 c e 9 2 5 1 4 1 6 4 5 f 0 0 1 6 6 f " , " g e n d e r " : 2 , " i d " : 1 3 8 3 3 8 9 , " n a m e " : " b e n r o b s o n " , " o r d e r " : 5 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " y o u n g b r a h m s h e e l s h i r e " , " c r e d i t _ i d " : " 5 6 4 f c 9 0 8 c 3 a 3 6 8 3 3 e 7 0 0 1 4 5 a " , " g e n d e r " : 0 , " i d " : 1 5 3 8 8 7 9 , " n a m e " : " j e t t k l y n e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " e m i l y c r i b b s " , " c r e d i t _ i d " : " 5 7 4 6 5 c f 4 c 3 a 3 6 8 0 6 a 1 0 0 0 d 5 5 " , " g e n d e r " : 0 , " i d " : 1 6 2 6 0 0 8 , " n a m e " : " l i l y p a t e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " s a n d y ( v o i c e ) " , " c r e d i t _ i d " : " 5 7 4 6 5 d 1 2 c 3 a 3 6 8 0 6 a 1 0 0 0 d 6 0 " , " g e n d e r " : 1 , " i d " : 2 2 2 1 3 9 , " n a m e " : " s t e p h a n i e l e m e l i n " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t a x i d r i v e r " , " c r e d i t _ i d " : " 5 7 4 6 5 d 0 6 9 2 5 1 4 1 5 e 6 5 0 0 0 b 9 5 " , " g e n d e r " : 2 , " i d " : 2 7 1 2 2 , " n a m e " : " m a t t h e w w a l k e r " , " o r d e r " : 9 } ]'

In [160]:
from sklearn.metrics.pairwise import cosine_similarity

In [162]:
similarity = cosine_similarity(vectors)

In [177]:
list(enumerate(similarity[0]))

[(0, np.float64(1.0)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.03742405942825599)),
 (4, np.float64(0.0)),
 (5, np.float64(0.0472455591261534)),
 (6, np.float64(0.0)),
 (7, np.float64(0.04652421051992355)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0)),
 (10, np.float64(0.04517539514526256)),
 (11, np.float64(0.0)),
 (12, np.float64(0.0)),
 (13, np.float64(0.0)),
 (14, np.float64(0.0)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0)),
 (19, np.float64(0.0)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.0)),
 (23, np.float64(0.05976143046671968)),
 (24, np.float64(0.0)),
 (25, np.float64(0.038575837490522985)),
 (26, np.float64(0.0)),
 (27, np.float64(0.08451542547285167)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.09166984970282112)),
 (31, np.float64(0.0)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.051434449987363975)),
 (38, np.float64(0.0)),
 (39, np.float64(0.07968190728895959)),
 (40, np.float64(0.0)),
 (41, np.float64(0.0)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.0)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.0)),
 (50, np.float64(0.0)),
 (51, np.float64(0.0)),
 (52, np.float64(0.0)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.0)),
 (56, np.float64(0.07412493166611013)),
 (57, np.float64(0.0)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.0)),
 (61, np.float64(0.09166984970282112)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.0)),
 (65, np.float64(0.0)),
 (66, np.float64(0.0)),
 (67, np.float64(0.0)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.058321184351980436)),
 (71, np.float64(0.0)),
 (72, np.float64(0.024603391565256146)),
 (73, np.float64(0.05241424183609592)),
 (74, np.float64(0.0)),
 (75, np.float64(0.0)),
 (76, np.float64(0.0)),
 (77, np.float64(0.0)),
 (78, np.float64(0.0)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.036369648372665396)),
 (82, np.float64(0.0)),
 (83, np.float64(0.0)),
 (84, np.float64(0.0)),
 (85, np.float64(0.0)),
 (86, np.float64(0.04225771273642583)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.0)),
 (91, np.float64(0.0)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.0)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.036369648372665396)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.048001536073731935)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.07412493166611013)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.028171808490950554)),
 (111, np.float64(0.0)),
 (112, np.float64(0.050507627227610534)),
 (113, np.float64(0.0)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.06299407883487121)),
 (117, np.float64(0.10438335009588318)),
 (118, np.float64(0.23904572186687872)),
 (119, np.float64(0.0)),
 (120, np.float64(0.03603749850782236)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.0)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0)),
 (126, np.float64(0.0)),
 (127, np.float64(0.0)),
 (128, np.float64(0.04393747751637468)),
 (129, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.04075695729696112)),
 (140, np.float64(0.0)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.0)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.10482848367219184)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.0)),
 (152, np.float64(0.03421929554145775)),
 (153, np.float64(0.0)),
 (154, np.float64(0.0)),
 (155, np.float64(0.0)),
 (156, np.float64(0.04652421051992355)),
 (157, np.float64(0.0)),
 (158, np.float64(0.0)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.0)),
 (165, np.float64(0.04652421051992355)),
 (166, np.float64(0.0)),
 (167, np.float64(0.03265115742241696)),
 (168, np.float64(0.0)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.037062465833055065)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.0)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.0)),
 (191, np.float64(0.0)),
 (192, np.float64(0.050507627227610534)),
 (193, np.float64(0.0)),
 (194, np.float64(0.03742405942825599)),
 (195, np.float64(0.0)),
 (196, np.float64(0.09925833339709303)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.0)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.0)),
 (208, np.float64(0.038180177416060626)),
 (209, np.float64(0.0)),
 (210, np.float64(0.050507627227610534)),
 (211, np.float64(0.0)),
 (212, np.float64(0.0)),
 (213, np.float64(0.09600307214746387)),
 (214, np.float64(0.0668153104781061)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.0)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.03421929554145775)),
 (229, np.float64(0.04173919355648411)),
 (230, np.float64(0.0)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0)),
 (241, np.float64(0.05572782125753529)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.0)),
 (247, np.float64(0.0)),
 (248, np.float64(0.0)),
 (249, np.float64(0.0)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.0)),
 (256, np.float64(0.0)),
 (257, np.float64(0.0)),
 (258, np.float64(0.0)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.0)),
 (262, np.float64(0.06900655593423542)),
 (263, np.float64(0.0)),
 (264, np.float64(0.03940552031195504)),
 (265, np.float64(0.0)),
 (266, np.float64(0.0)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.0)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0)),
 (278, np.float64(0.0)),
 (279, np.float64(0.0)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.06482037235521644)),
 (286, np.float64(0.0)),
 (287, np.float64(0.05241424183609592)),
 (288, np.float64(0.0)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.0)),
 (296, np.float64(0.08058229640253803)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.0)),
 (300, np.float64(0.0)),
 (301, np.float64(0.0)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.0)),
 (311, np.float64(0.0)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.049629166698546515)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.12262786789699316)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.053452248382484885)),
 (332, np.float64(0.0)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0472455591261534)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.0)),
 (345, np.float64(0.0)),
 (346, np.float64(0.0668153104781061)),
 (347, np.float64(0.0668153104781061)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.04879500364742666)),
 (355, np.float64(0.1336306209562122)),
 (356, np.float64(0.06131393394849658)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.04583492485141056)),
 (362, np.float64(0.0)),
 (363, np.float64(0.0)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.06482037235521644)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.0)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.04879500364742666)),
 (389, np.float64(0.0)),
 (390, np.float64(0.0)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.0)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0)),
 (401, np.float64(0.0)),
 (402, np.float64(0.0)),
 (403, np.float64(0.0)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.0)),
 (409, np.float64(0.0)),
 (410, np.float64(0.0)),
 (411, np.float64(0.0)),
 (412, np.float64(0.0)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.0)),
 (419, np.float64(0.0)),
 (420, np.float64(0.0)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.0445435403187374)),
 (426, np.float64(0.0)),
 (427, np.float64(0.0)),
 (428, np.float64(0.0)),
 (429, np.float64(0.04173919355648411)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.04652421051992355)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0)),
 (442, np.float64(0.0)),
 (443, np.float64(0.0)),
 (444, np.float64(0.0)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.09235141930792204)),
 (448, np.float64(0.0)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.0)),
 (455, np.float64(0.0445435403187374)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.05241424183609592)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.06131393394849658)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0)),
 (476, np.float64(0.0)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.0)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.0)),
 (489, np.float64(0.0)),
 (490, np.float64(0.0)),
 (491, np.float64(0.0)),
 (492, np.float64(0.0)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.0)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.0)),
 (500, np.float64(0.0)),
 (501, np.float64(0.0)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.03603749850782236)),
 (505, np.float64(0.0)),
 (506, np.float64(0.0)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.048001536073731935)),
 (510, np.float64(0.0)),
 (511, np.float64(0.05698028822981897)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.0)),
 (524, np.float64(0.0)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.0)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.0)),
 (536, np.float64(0.0)),
 (537, np.float64(0.0)),
 (538, np.float64(0.0)),
 (539, np.float64(0.04879500364742666)),
 (540, np.float64(0.0)),
 (541, np.float64(0.0)),
 (542, np.float64(0.0)),
 (543, np.float64(0.0)),
 (544, np.float64(0.0)),
 (545, np.float64(0.0)),
 (546, np.float64(0.0)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.0)),
 (551, np.float64(0.0)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.10910894511799621)),
 (556, np.float64(0.0)),
 (557, np.float64(0.0)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.0)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0)),
 (571, np.float64(0.0)),
 (572, np.float64(0.0)),
 (573, np.float64(0.0)),
 (574, np.float64(0.08451542547285167)),
 (575, np.float64(0.0)),
 (576, np.float64(0.0)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.1286978904175574)),
 (580, np.float64(0.0472455591261534)),
 (581, np.float64(0.0)),
 (582, np.float64(0.0)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.0)),
 (586, np.float64(0.0)),
 (587, np.float64(0.0)),
 (588, np.float64(0.0)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.0)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.06482037235521644)),
 (595, np.float64(0.0)),
 (596, np.float64(0.0)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.0)),
 (600, np.float64(0.0)),
 (601, np.float64(0.038984058779272523)),
 (602, np.float64(0.0)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.0)),
 (607, np.float64(0.0890870806374748)),
 (608, np.float64(0.041239304942116126)),
 (609, np.float64(0.0)),
 (610, np.float64(0.06900655593423542)),
 (611, np.float64(0.0)),
 (612, np.float64(0.0)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.0)),
 (619, np.float64(0.0)),
 (620, np.float64(0.0)),
 (621, np.float64(0.0)),
 (622, np.float64(0.07412493166611013)),
 (623, np.float64(0.0)),
 (624, np.float64(0.0)),
 (625, np.float64(0.038984058779272523)),
 (626, np.float64(0.0)),
 (627, np.float64(0.0)),
 (628, np.float64(0.0)),
 (629, np.float64(0.03421929554145775)),
 (630, np.float64(0.0)),
 (631, np.float64(0.0)),
 (632, np.float64(0.0)),
 (633, np.float64(0.0)),
 (634, np.float64(0.0)),
 (635, np.float64(0.0)),
 (636, np.float64(0.0)),
 (637, np.float64(0.0)),
 (638, np.float64(0.0)),
 (639, np.float64(0.0)),
 (640, np.float64(0.05241424183609592)),
 (641, np.float64(0.0)),
 (642, np.float64(0.0)),
 (643, np.float64(0.0)),
 (644, np.float64(0.0)),
 (645, np.float64(0.0)),
 (646, np.float64(0.0)),
 (647, np.float64(0.0)),
 (648, np.float64(0.0)),
 (649, np.float64(0.0)),
 (650, np.float64(0.0)),
 (651, np.float64(0.0)),
 (652, np.float64(0.0)),
 (653, np.float64(0.0)),
 (654, np.float64(0.0)),
 (655, np.float64(0.0)),
 (656, np.float64(0.0)),
 (657, np.float64(0.0)),
 (658, np.float64(0.0)),
 (659, np.float64(0.0)),
 (660, np.float64(0.0)),
 (661, np.float64(0.0)),
 (662, np.float64(0.0)),
 (663, np.float64(0.0)),
 (664, np.float64(0.0)),
 (665, np.float64(0.08058229640253803)),
 (666, np.float64(0.0)),
 (667, np.float64(0.0)),
 (668, np.float64(0.0)),
 (669, np.float64(0.0)),
 (670, np.float64(0.0)),
 (671, np.float64(0.0)),
 (672, np.float64(0.0)),
 (673, np.float64(0.0)),
 (674, np.float64(0.0)),
 (675, np.float64(0.048001536073731935)),
 (676, np.float64(0.0)),
 (677, np.float64(0.0)),
 (678, np.float64(0.0)),
 (679, np.float64(0.050507627227610534)),
 (680, np.float64(0.0)),
 (681, np.float64(0.049629166698546515)),
 (682, np.float64(0.0)),
 (683, np.float64(0.0)),
 (684, np.float64(0.0)),
 (685, np.float64(0.0)),
 (686, np.float64(0.0)),
 (687, np.float64(0.0)),
 (688, np.float64(0.0)),
 (689, np.float64(0.0)),
 (690, np.float64(0.0)),
 (691, np.float64(0.0)),
 (692, np.float64(0.0)),
 (693, np.float64(0.0)),
 (694, np.float64(0.0)),
 (695, np.float64(0.0)),
 (696, np.float64(0.0)),
 (697, np.float64(0.0)),
 (698, np.float64(0.0)),
 (699, np.float64(0.0)),
 (700, np.float64(0.0)),
 (701, np.float64(0.051434449987363975)),
 (702, np.float64(0.0)),
 (703, np.float64(0.0)),
 (704, np.float64(0.0)),
 (705, np.float64(0.0)),
 (706, np.float64(0.0)),
 (707, np.float64(0.0)),
 (708, np.float64(0.050507627227610534)),
 (709, np.float64(0.12598815766974242)),
 (710, np.float64(0.0)),
 (711, np.float64(0.0)),
 (712, np.float64(0.0)),
 (713, np.float64(0.0)),
 (714, np.float64(0.0)),
 (715, np.float64(0.0)),
 (716, np.float64(0.0)),
 (717, np.float64(0.07881104062391008)),
 (718, np.float64(0.0)),
 (719, np.float64(0.0)),
 (720, np.float64(0.0)),
 (721, np.float64(0.04173919355648411)),
 (722, np.float64(0.0)),
 (723, np.float64(0.0)),
 (724, np.float64(0.08151391459392224)),
 (725, np.float64(0.0)),
 (726, np.float64(0.0)),
 (727, np.float64(0.0)),
 (728, np.float64(0.0)),
 (729, np.float64(0.0)),
 (730, np.float64(0.0)),
 (731, np.float64(0.0)),
 (732, np.float64(0.039840953644479794)),
 (733, np.float64(0.0)),
 (734, np.float64(0.0)),
 (735, np.float64(0.0)),
 (736, np.float64(0.0)),
 (737, np.float64(0.0)),
 (738, np.float64(0.0)),
 (739, np.float64(0.0)),
 (740, np.float64(0.0)),
 (741, np.float64(0.0)),

In [184]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [173]:
new_df[new_df['title'] == 'Avatar'].index[0]

np.int64(0)

In [175]:
sorted(similarity[0],reverse= True)

[np.float64(1.0),
 np.float64(0.24743582965269675),
 np.float64(0.23904572186687872),
 np.float64(0.1336306209562122),
 np.float64(0.1286978904175574),
 np.float64(0.12598815766974242),
 np.float64(0.12598815766974242),
 np.float64(0.12262786789699316),
 np.float64(0.1182165609358651),
 np.float64(0.11396057645963795),
 np.float64(0.10910894511799621),
 np.float64(0.10482848367219184),
 np.float64(0.10438335009588318),
 np.float64(0.09925833339709303),
 np.float64(0.09600307214746387),
 np.float64(0.0944911182523068),
 np.float64(0.09235141930792204),
 np.float64(0.09166984970282112),
 np.float64(0.09166984970282112),
 np.float64(0.0890870806374748),
 np.float64(0.08451542547285167),
 np.float64(0.08451542547285167),
 np.float64(0.08151391459392224),
 np.float64(0.08058229640253803),
 np.float64(0.08058229640253803),
 np.float64(0.07968190728895959),
 np.float64(0.07881104062391008),
 np.float64(0.07715167498104597),
 np.float64(0.07715167498104597),
 np.float64(0.07412493166611013),
 np.float64(0.07412493166611013),
 np.float64(0.07412493166611013),
 np.float64(0.07142857142857144),
 np.float64(0.06900655593423542),
 np.float64(0.06900655593423542),
 np.float64(0.06900655593423542),
 np.float64(0.06900655593423542),
 np.float64(0.06900655593423542),
 np.float64(0.06900655593423542),
 np.float64(0.0668153104781061),
 np.float64(0.0668153104781061),
 np.float64(0.0668153104781061),
 np.float64(0.06482037235521644),
 np.float64(0.06482037235521644),
 np.float64(0.06482037235521644),
 np.float64(0.06482037235521644),
 np.float64(0.06482037235521644),
 np.float64(0.06482037235521644),
 np.float64(0.06299407883487121),
 np.float64(0.06299407883487121),
 np.float64(0.06299407883487121),
 np.float64(0.06131393394849658),
 np.float64(0.06131393394849658),
 np.float64(0.06131393394849658),
 np.float64(0.06131393394849658),
 np.float64(0.05976143046671968),
 np.float64(0.05976143046671968),
 np.float64(0.058321184351980436),
 np.float64(0.058321184351980436),
 np.float64(0.058321184351980436),
 np.float64(0.05698028822981897),
 np.float64(0.05698028822981897),
 np.float64(0.05698028822981897),
 np.float64(0.05572782125753529),
 np.float64(0.05572782125753529),
 np.float64(0.054554472558998104),
 np.float64(0.054554472558998104),
 np.float64(0.053452248382484885),
 np.float64(0.053452248382484885),
 np.float64(0.053452248382484885),
 np.float64(0.05241424183609592),
 np.float64(0.05241424183609592),
 np.float64(0.05241424183609592),
 np.float64(0.05241424183609592),
 np.float64(0.05241424183609592),
 np.float64(0.05241424183609592),
 np.float64(0.051434449987363975),
 np.float64(0.051434449987363975),
 np.float64(0.051434449987363975),
 np.float64(0.050507627227610534),
 np.float64(0.050507627227610534),
 np.float64(0.050507627227610534),
 np.float64(0.050507627227610534),
 np.float64(0.050507627227610534),
 np.float64(0.049629166698546515),
 np.float64(0.049629166698546515),
 np.float64(0.04879500364742666),
 np.float64(0.04879500364742666),
 np.float64(0.04879500364742666),
 np.float64(0.04879500364742666),
 np.float64(0.048001536073731935),
 np.float64(0.048001536073731935),
 np.float64(0.048001536073731935),
 np.float64(0.0472455591261534),
 np.float64(0.0472455591261534),
 np.float64(0.0472455591261534),
 np.float64(0.04652421051992355),
 np.float64(0.04652421051992355),
 np.float64(0.04652421051992355),
 np.float64(0.04652421051992355),
 np.float64(0.04652421051992355),
 np.float64(0.04652421051992355),
 np.float64(0.04583492485141056),
 np.float64(0.04583492485141056),
 np.float64(0.04583492485141056),
 np.float64(0.04583492485141056),
 np.float64(0.04517539514526256),
 np.float64(0.04517539514526256),
 np.float64(0.04517539514526256),
 np.float64(0.0445435403187374),
 np.float64(0.0445435403187374),
 np.float64(0.04393747751637468),
 np.float64(0.04393747751637468),
 np.float64(0.04225771273642583),
 np.float64(0.04225771273642583),
 np.float64(0.04173919355648411),
 np.float64(0.04173919355648411),
 np.float64(0.04173919355648411),
 np.float64(0.04173919355648411),
 np.float64(0.041239304942116126),
 np.float64(0.041239304942116126),
 np.float64(0.041239304942116126),
 np.float64(0.04075695729696112),
 np.float64(0.04075695729696112),
 np.float64(0.039840953644479794),
 np.float64(0.039840953644479794),
 np.float64(0.03940552031195504),
 np.float64(0.03940552031195504),
 np.float64(0.03940552031195504),
 np.float64(0.038984058779272523),
 np.float64(0.038984058779272523),
 np.float64(0.038984058779272523),
 np.float64(0.038575837490522985),
 np.float64(0.038575837490522985),
 np.float64(0.038575837490522985),
 np.float64(0.038180177416060626),
 np.float64(0.038180177416060626),
 np.float64(0.03779644730092272),
 np.float64(0.03742405942825599),
 np.float64(0.03742405942825599),
 np.float64(0.03742405942825599),
 np.float64(0.037062465833055065),
 np.float64(0.037062465833055065),
 np.float64(0.037062465833055065),
 np.float64(0.036369648372665396),
 np.float64(0.036369648372665396),
 np.float64(0.03603749850782236),
 np.float64(0.03603749850782236),
 np.float64(0.03603749850782236),
 np.float64(0.03603749850782236),
 np.float64(0.03421929554145775),
 np.float64(0.03421929554145775),
 np.float64(0.03421929554145775),
 np.float64(0.03367175148507369),
 np.float64(0.03289758474798845),
 np.float64(0.03265115742241696),
 np.float64(0.03241018617760822),
 np.float64(0.028171808490950554),
 np.float64(0.024603391565256146),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),

In [185]:
recommend('Batman Begins')

Kung Fu Panda 2
A Dog's Breakfast
Hereafter
The Little Prince
The Hobbit: An Unexpected Journey

In [186]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [187]:
new_df[new_df['title'] == 'Batman Begins']

,movie_id,title,tags
119,272,Batman Begins,"driven by tragedy, billionair bruce wayn dedic..."

In [188]:
print(new_df['tags'].iloc[0])

in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. [ { " i d " : 2 8 , " n a m e " : " a c t i o n " } , { " i d " : 1 2 , " n a m e " : " a d v e n t u r e " } , { " i d " : 1 4 , " n a m e " : " f a n t a s y " } , { " i d " : 8 7 8 , " n a m e " : " s c i e n c e f i c t i o n " } ] [ { " i d " : 1 4 6 3 , " n a m e " : " c u l t u r e c l a s h " } , { " i d " : 2 9 6 4 , " n a m e " : " f u t u r e " } , { " i d " : 3 3 8 6 , " n a m e " : " s p a c e w a r " } , { " i d " : 3 3 8 8 , " n a m e " : " s p a c e c o l o n y " } , { " i d " : 3 6 7 9 , " n a m e " : " s o c i e t y " } , { " i d " : 3 8 0 1 , " n a m e " : " s p a c e t r a v e l " } , { " i d " : 9 6 8 5 , " n a m e " : " f u t u r i s t i c " } , { " i d " : 9 8 4 0 , " n a m e " : " r o m a n c e " } , { " i d " : 9 8 8 2 , " n a m e " : " s p a c e " } , { " i d " : 9 9 5 1 , " n a m e " : " a l i e n " } , { " i d " : 1 0 1 4 8 , " n a m e " : " t r i b e " } , { " i d " : 1 0 1 5 8 , " n a m e " : " a l i e n p l a n e t " } , { " i d " : 1 0 9 8 7 , " n a m e " : " c g i " } , { " i d " : 1 1 3 9 9 , " n a m e " : " m a r i n e " } , { " i d " : 1 3 0 6 5 , " n a m e " : " s o l d i e r " } , { " i d " : 1 4 6 4 3 , " n a m e " : " b a t t l e " } , { " i d " : 1 4 7 2 0 , " n a m e " : " l o v e a f f a i r " } , { " i d " : 1 6 5 4 3 1 , " n a m e " : " a n t i w a r " } , { " i d " : 1 9 3 5 5 4 , " n a m e " : " p o w e r r e l a t i o n s " } , { " i d " : 2 0 6 6 9 0 , " n a m e " : " m i n d a n d s o u l " } , { " i d " : 2 0 9 7 1 4 , " n a m e " : " 3 d " } ] [ { " c a s t _ i d " : 2 4 2 , " c h a r a c t e r " : " j a k e s u l l y " , " c r e d i t _ i d " : " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " , " g e n d e r " : 2 , " i d " : 6 5 7 3 1 , " n a m e " : " s a m w o r t h i n g t o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " n e y t i r i " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " , " g e n d e r " : 1 , " i d " : 8 6 9 1 , " n a m e " : " z o e s a l d a n a " , " o r d e r " : 1 } , { " c a s t _ i d " : 2 5 , " c h a r a c t e r " : " d r . g r a c e a u g u s t i n e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " , " g e n d e r " : 1 , " i d " : 1 0 2 0 5 , " n a m e " : " s i g o u r n e y w e a v e r " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " c o l . q u a r i t c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " , " g e n d e r " : 2 , " i d " : 3 2 7 4 7 , " n a m e " : " s t e p h e n l a n g " , " o r d e r " : 3 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " t r u d y c h a c o n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " , " g e n d e r " : 1 , " i d " : 1 7 6 4 7 , " n a m e " : " m i c h e l l e r o d r i g u e z " , " o r d e r " : 4 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " s e l f r i d g e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " , " g e n d e r " : 2 , " i d " : 1 7 7 1 , " n a m e " : " g i o v a n n i r i b i s i " , " o r d e r " : 5 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " n o r m s p e l l m a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " , " g e n d e r " : 2 , " i d " : 5 9 2 3 1 , " n a m e " : " j o e l d a v i d m o o r e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " m o a t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " , " g e n d e r " : 1 , " i d " : 3 0 4 8 5 , " n a m e " : " c c h p o u n d e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " e y t u k a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " , " g e n d e r " : 2 , " i d " : 1 5 8 5 3 , " n a m e " : " w e s s t u d i " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t s u ' t e y " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " , " g e n d e r " : 2 , " i d " : 1 0 9 6 4 , " n a m e " : " l a z a l o n s o " , " o r d e r " : 9 } , { " c a s t _ i d " : 1 2 , " c h a r a c t e r " : " d r . m a x p a t e l " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " , " g e n d e r " : 2 , " i d " : 9 5 6 9 7 , " n a m e " : " d i l e e p r a o " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " l y l e w a i n f l e e t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " , " g e n d e r " : 2 , " i d " : 9 8 2 1 5 , " n a m e " : " m a t t g e r a l d " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " p r i v a t e f i k e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " , " g e n d e r " : 2 , " i d " : 1 5 4 1 5 3 , " n a m e " : " s e a n a n t h o n y m o r a n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " c r y o v a u l t m e d t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " , " g e n d e r " : 2 , " i d " : 3 9 7 3 1 2 , " n a m e " : " j a s o n w h y t e " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " v e n t u r e s t a r c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " , " g e n d e r " : 2 , " i d " : 4 2 3 1 7 , " n a m e " : " s c o t t l a w r e n c e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " l o c k u p t r o o p e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " , " g e n d e r " : 2 , " i d " : 9 8 6 7 3 4 , " n a m e " : " k e l l y k i l g o u r " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " s h u t t l e p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 2 7 , " n a m e " : " j a m e s p a t r i c k p i t t " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " s h u t t l e c o - p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " , " g e n d e r " : 0 , " i d " : 1 1 8 0 9 3 6 , " n a m e " : " s e a n p a t r i c k m u r p h y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " s h u t t l e c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " , " g e n d e r " : 2 , " i d " : 1 0 1 9 5 7 8 , " n a m e " : " p e t e r d i l l o n " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " t r a c t o r o p e r a t o r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " , " g e n d e r " : 0 , " i d " : 9 1 4 4 3 , " n a m e " : " k e v i n d o r m a n " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " d r a g o n g u n s h i p p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " , " g e n d e r " : 2 , " i d " : 1 7 3 3 9 1 , " n a m e " : " k e l s o n h e n d e r s o n " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " d r a g o n g u n s h i p g u n n e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 3 6 , " n a m e " : " d a v i d v a n h o r n " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " d r a g o n g u n s h i p n a v i g a t o r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " , " g e n d e r " : 0 , " i d " : 2 1 5 9 1 3 , " n a m e " : " j a c o b t o m u r i " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s u i t # 1 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " , " g e n d e r " : 0 , " i d " : 1 4 3 2 0 6 , " n a m e " : " m i c h a e l b l a i n - r o z g a y " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " s u i t # 2 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " , " g e n d e r " : 2 , " i d " : 1 6 9 6 7 6 , " n a m e " : " j o n c u r r y " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " , " g e n d e r " : 0 , " i d " : 1 0 4 8 6 1 0 , " n a m e " : " l u k e h a w k e r " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " n a m e " : " w o o d y s c h u l t z " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " h o r s e c l a n l e a d e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " , " g e n d e r " : 2 , " i d " : 6 8 2 7 8 , " n a m e " : " p e t e r m e n s a h " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " l i n k r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 7 , " n a m e " : " s o n i a y e e " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " , " g e n d e r " : 1 , " i d " : 1 2 0 7 2 4 8 , " n a m e " : " j a h n e l c u r f m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " n a m e " : " i l r a m c h o i " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " n a ' v i c h i l d " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 9 , " n a m e " : " k y l a w a r r e n " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 0 , " n a m e " : " l i s a r o u m a i n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " , " g e n d e r " : 1 , " i d " : 8 3 1 0 5 , " n a m e " : " d e b r a w i l s o n " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 3 , " n a m e " : " c h r i s m a l a " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 1 , " n a m e " : " t a y l o r k i b b y " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 2 , " n a m e " : " j o d i e l a n d a u " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 4 , " n a m e " : " j u l i e l a m m " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 7 , " n a m e " : " c u l l e n b . m a d d e n " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 9 , " n a m e " : " j o s e p h b r a d y m a d d e n " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 2 , " n a m e " : " f r a n k i e t o r r e s " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " , " g e n d e r " : 1 , " i d " : 1 1 5 8 6 0 0 , " n a m e " : " a u s t i n w i l s o n " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " , " g e n d e r " : 1 , " i d " : 9 8 3 7 0 5 , " n a m e " : " s a r a w i l s o n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 3 , " n a m e " : " t a m i c a w a s h i n g t o n - m i l l e r " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " , " g e n d e r " : 1 , " i d " : 1 1 4 5 0 9 8 , " n a m e " : " l u c y b r i a n t " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " , " g e n d e r " : 2 , " i d " : 3 3 3 0 5 , " n a m e " : " n a t h a n m e i s t e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 4 , " n a m e " : " g e r r y b l a i r " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " , " g e n d e r " : 2 , " i d " : 3 3 3 1 1 , " n a m e " : " m a t t h e w c h a m b e r l a i n " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 5 , " n a m e " : " p a u l y a t e s " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " o p c e n t e r d u t y o f f i c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 6 , " n a m e " : " w r a y w i l s o n " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " , " g e n d e r " : 2 , " i d " : 5 4 4 9 2 , " n a m e " : " j a m e s g a y l y n " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 7 , " n a m e " : " m e l v i n l e n o c l a r k i i i " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 8 , " n a m e " : " c a r v o n f u t r e l l " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 9 , " n a m e " : " b r a n d o n j e l k e s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 0 , " n a m e " : " m i c a h m o c h " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 1 , " n a m e " : " h a n n i y a h m u h a m m a d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 7 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 2 , " n a m e " : " c h r i s t o p h e r n o l e n " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 8 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 3 , " n a m e " : " c h r i s t a o l i v e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 9 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 4 , " n a m e " : " a p r i l m a r i e t h o m a s " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 8 0 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 5 , " n a m e " : " b r a v i t a a . t h r e a t t " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 8 1 , " c h a r a c t e r " : " m i n i n g c h i e f ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 6 , " n a m e " : " c o l i n b l e a s d a l e " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 8 2 , " c h a r a c t e r " : " v e t e r a n m i n e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " , " g e n d e r " : 0 , " i d " : 1 0 7 9 6 9 , " n a m e " : " m i k e b o d n a r " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 8 3 , " c h a r a c t e r " : " r i c h a r d ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 8 , " n a m e " : " m a t t c l a y t o n " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 8 4 , " c h a r a c t e r " : " n a v ' i ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " , " g e n d e r " : 1 , " i d " : 1 4 7 8 9 8 , " n a m e " : " n i c o l e d i o n n e " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 8 5 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 0 , " n a m e " : " j a m i e h a r r i s o n " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 8 6 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 1 , " n a m e " : " a l l a n h e n r y " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 8 7 , " c h a r a c t e r " : " g r o u n d t e c h n i c i a n ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " , " g e n d e r " : 2 , " i d " : 1 2 0

In [189]:
print(similarity.shape)
print(new_df.shape)

(1494, 1494)
(1494, 3)

In [190]:
new_df.shape
similarity.shape
new_df[new_df['title'] == 'Batman Begins']
print(new_df[new_df['title'] == 'Batman Begins']['tags'].values[0])

driven by tragedy, billionair bruce wayn dedic hi life to uncov and defeat the corrupt that plagu hi home, gotham city. unabl to work within the system, he instead creat a new identity, a symbol of fear for the crimin underworld - the batman. [ { " i d " : 2 8 , " n a m e " : " a c t i o n " } , { " i d " : 8 0 , " n a m e " : " c r i m e " } , { " i d " : 1 8 , " n a m e " : " d r a m a " } ] [ { " i d " : 4 8 6 , " n a m e " : " h i m a l a y a " } , { " i d " : 7 7 9 , " n a m e " : " m a r t i a l a r t s " } , { " i d " : 8 4 9 , " n a m e " : " d c c o m i c s " } , { " i d " : 8 5 3 , " n a m e " : " c r i m e f i g h t e r " } , { " i d " : 1 3 0 8 , " n a m e " : " s e c r e t i d e n t i t y " } , { " i d " : 1 5 6 8 , " n a m e " : " u n d e r c o v e r " } , { " i d " : 1 7 0 1 , " n a m e " : " h e r o " } , { " i d " : 1 8 7 2 , " n a m e " : " l o s s o f f a t h e r " } , { " i d " : 3 6 7 9 , " n a m e " : " s o c i e t y " } , { " i d " : 6 9 6 9 , " n a m e " : " g o t h a m c i t y " } , { " i d " : 7 0 0 2 , " n a m e " : " v i g i l a n t e " } , { " i d " : 9 7 1 5 , " n a m e " : " s u p e r h e r o " } , { " i d " : 9 7 1 7 , " n a m e " : " b a s e d o n c o m i c b o o k " } , { " i d " : 9 8 2 3 , " n a m e " : " r i v a l r y " } , { " i d " : 1 0 0 4 4 , " n a m e " : " t r a g i c h e r o " } , { " i d " : 1 0 2 7 8 , " n a m e " : " n i n j a " } , { " i d " : 1 0 8 4 2 , " n a m e " : " g o o d v s e v i l " } , { " i d " : 1 4 5 3 6 , " n a m e " : " c r i m e " } , { " i d " : 1 6 3 4 5 5 , " n a m e " : " s u p e r p o w e r s " } , { " i d " : 1 7 3 7 1 9 , " n a m e " : " h a u n t e d b y t h e p a s t " } , { " i d " : 1 7 9 0 9 5 , " n a m e " : " e v i l d o c t o r " } , { " i d " : 1 8 7 7 1 0 , " n a m e " : " e s c a p a d e " } , { " i d " : 2 0 6 6 9 4 , " n a m e " : " m a s t e r v i l l a i n " } , { " i d " : 2 0 6 7 0 0 , " n a m e " : " f i g h t i n g c r i m e " } , { " i d " : 2 0 6 7 0 9 , " n a m e " : " u n f u l f i l l m e n t " } , { " i d " : 2 0 6 7 1 5 , " n a m e " : " l o v e a n d r o m a n c e " } , { " i d " : 2 0 6 7 1 6 , " n a m e " : " u n f u l f i l l e d l o v e " } ] [ { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " b r u c e w a y n e / b a t m a n " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 3 d " , " g e n d e r " : 2 , " i d " : 3 8 9 4 , " n a m e " : " c h r i s t i a n b a l e " , " o r d e r " : 0 } , { " c a s t _ i d " : 1 4 , " c h a r a c t e r " : " a l f r e d p e n n y w o r t h " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 4 1 " , " g e n d e r " : 2 , " i d " : 3 8 9 5 , " n a m e " : " m i c h a e l c a i n e " , " o r d e r " : 1 } , { " c a s t _ i d " : 1 5 , " c h a r a c t e r " : " h e n r i d u c a r d " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 4 5 " , " g e n d e r " : 2 , " i d " : 3 8 9 6 , " n a m e " : " l i a m n e e s o n " , " o r d e r " : 2 } , { " c a s t _ i d " : 1 6 , " c h a r a c t e r " : " r a c h e l d a w e s " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 4 9 " , " g e n d e r " : 1 , " i d " : 3 8 9 7 , " n a m e " : " k a t i e h o l m e s " , " o r d e r " : 3 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " j i m g o r d o n " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 3 5 " , " g e n d e r " : 2 , " i d " : 6 4 , " n a m e " : " g a r y o l d m a n " , " o r d e r " : 4 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " d r . j o n a t h a n c r a n e / s c a r e c r o w " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 3 9 " , " g e n d e r " : 2 , " i d " : 2 0 3 7 , " n a m e " : " c i l l i a n m u r p h y " , " o r d e r " : 5 } , { " c a s t _ i d " : 2 9 , " c h a r a c t e r " : " c a r m i n e f a l c o n e " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 1 " , " g e n d e r " : 2 , " i d " : 2 0 7 , " n a m e " : " t o m w i l k i n s o n " , " o r d e r " : 6 } , { " c a s t _ i d " : 3 1 , " c h a r a c t e r " : " l u c i u s f o x " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 5 " , " g e n d e r " : 2 , " i d " : 1 9 2 , " n a m e " : " m o r g a n f r e e m a n " , " o r d e r " : 7 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " e a r l e " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 9 " , " g e n d e r " : 2 , " i d " : 5 8 5 , " n a m e " : " r u t g e r h a u e r " , " o r d e r " : 8 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " r a ' s a l g h u l " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 d " , " g e n d e r " : 2 , " i d " : 3 8 9 9 , " n a m e " : " k e n w a t a n a b e " , " o r d e r " : 9 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " f l a s s " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 1 " , " g e n d e r " : 2 , " i d " : 5 3 4 , " n a m e " : " m a r k b o o n e j u n i o r " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " t h o m a s w a y n e " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 5 " , " g e n d e r " : 2 , " i d " : 3 9 0 0 , " n a m e " : " l i n u s r o a c h e " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " f i n c h " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 9 " , " g e n d e r " : 2 , " i d " : 5 4 4 , " n a m e " : " l a r r y h o l d e n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " j u d g e f a d e n " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 d " , " g e n d e r " : 0 , " i d " : 1 5 1 9 4 3 , " n a m e " : " g e r a r d m u r p h y " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " l o e b " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 9 1 " , " g e n d e r " : 2 , " i d " : 1 2 8 3 8 6 , " n a m e " : " c o l i n m c f a r l a n e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " l i t t l e b o y " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 9 5 " , " g e n d e r " : 2 , " i d " : 4 8 9 4 6 7 , " n a m e " : " j a c k g l e e s o n " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " c r a n e t h u g # 1 " , " c r e d i t _ i d " : " 5 3 6 a 3 1 8 7 0 e 0 a 2 6 4 7 c 4 0 0 a 1 4 d " , " g e n d e r " : 0 , " i d " : 1 3 1 7 3 9 7 , " n a m e " : " t . j . r a m i n i " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 1 8 9 , " c h a r a c t e r " : " c r a n e t h u g # 2 " , " c r e d i t _ i d " : " 5 8 0 4 f 4 1 4 c 3 a 3 6 8 6 a 3 4 0 0 0 9 7 a " , " g e n d e r " : 2 , " i d " : 1 6 9 5 9 6 0 , " n a m e " : " k i e r a n h u r l e y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " b l o n d e f e m a l e r e p o r t e r / a s s a s s i n " , " c r e d i t _ i d " : " 5 3 a a 4 d 4 a c 3 a 3 6 8 4 c f b 0 0 0 d 9 3 " , " g e n d e r " : 0 , " i d " : 1 3 3 4 1 2 4 , " n a m e " : " c a t h e r i n e p o r t e r " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " b r u c e w a y n e a l s k i n d " , " c r e d i t _ i d " : " 5 4 e 2 7 d e 7 c 3 a 3 6 8 0 8 7 b 0 0 2 3 d d " , " g e n d e r " : 2 , " i d " : 1 1 7 2 3 7 1 , " n a m e " : " g u s l e w i s " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " h o m e l e s s m a n " , " c r e d i t _ i d " : " 5 5 5 c 3 2 d 4 9 2 5 1 4 1 6 b 5 d 0 0 0 a 2 0 " , " g e n d e r " : 2 , " i d " : 1 1 1 8 , " n a m e " : " r a d e s e r b e d z i j a " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " m a r t h a w a y n e " , " c r e d i t _ i d " : " 5 5 c b 7 b 9 3 9 2 5 1 4 1 7 6 4 8 0 0 0 0 a 3 " , " g e n d e r " : 1 , " i d " : 3 9 0 2 , " n a m e " : " s a r a s t e w a r t " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " j o e c h i l l " , " c r e d i t _ i d " : " 5 5 c b 7 b d 0 9 2 5 1 4 1 7 6 4 5 0 0 0 0 f 8 " , " g e n d e r " : 2 , " i d " : 3 9 0 1 , " n a m e " : " r i c h a r d b r a k e " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " r a c h e l d a w e s - a g e 8 " , " c r e d i t _ i d " : " 5 5 c b 7 b f 5 9 2 5 1 4 1 7 6 4 f 0 0 0 0 c 6 " , " g e n d e r " : 1 , " i d " : 7 8 1 1 4 , " n a m e " : " e m m a l o c k h a r t " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " j e s s i c a " , " c r e d i t _ i d " : " 5 5 c b 7 c 2 2 c 3 a 3 6 8 5 6 f 9 0 0 0 0 d 7 " , " g e n d e r " : 1 , " i d " : 8 7 1 9 4 , " n a m e " : " c h r i s t i n e a d a m s " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " f r e d e r i c k s " , " c r e d i t _ i d " : " 5 5 c b 7 c 4 0 c 3 a 3 6 8 5 6 f b 0 0 0 0 e e " , " g e n d e r " : 2 , " i d " : 7 0 2 2 5 , " n a m e " : " j o h n n o l a n " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " c o u r t h o u s e r e p o r t e r # 1 " , " c r e d i t _ i d " : " 5 5 c b 7 c 6 8 9 2 5 1 4 1 7 6 4 b 0 0 0 1 0 7 " , " g e n d e r " : 1 , " i d " : 7 9 1 2 4 , " n a m e " : " k a r e n d a v i d " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 1 6 1 , " c h a r a c t e r " : " c o u r t h o u s e r e p o r t e r # 2 " , " c r e d i t _ i d " : " 5 7 f 7 b b 6 f c 3 a 3 6 8 3 a a 7 0 0 2 9 4 f " , " g e n d e r " : 2 , " i d " : 1 6 9 0 7 7 3 , " n a m e " : " j o n a t h a n d . e l l i s " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " f a d e n ' s l i m o d r i v e r " , " c r e d i t _ i d " : " 5 5 c b 7 c a 9 c 3 a 3 6 8 5 7 0 8 0 0 0 0 d 3 " , " g e n d e r " : 2 , " i d " : 3 9 6 6 0 , " n a m e " : " t a m e r h a s s a n " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " u n i f o r m e d p o l i c e m a n # 1 " , " c r e d i t _ i d " : " 5 5 c b 7 c b f c 3 a 3 6 8 5 7 0 4 0 0 0 1 7 4 " , " g e n d e r " : 2 , " i d " : 5 5 9 2 0 9 , " n a m e " : " r o n a n l e a h y " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " o l d a s i a n p r i s o n e r " , " c r e d i t _ i d " : " 5 5 c b 7 c d b c 3 a 3 6 8 5 6 f e 0 0 0 1 2 7 " , " g e n d e r " : 2 , " i d " : 1 2 5 7 8 2 1 , " n a m e " : " v i n c e n t w o n g " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " b h u t a n e s e p r i s o n g u a r d # 1 " , " c r e d i t _ i d " : " 5 5 c b 7 c f 2 9 2 5 1 4 1 7 6 3 9 0 0 0 1 0 4 " , " g e n d e r " : 2 , " i d " : 6 7 2 1 2 , " n a m e " : " t o m w u " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 1 6 2 , " c h a r a c t e r " : " b h u t a n e s e p r i s o n g u a r d # 2 " , " c r e d i t _ i d " : " 5 7 f 8 0 3 c 2 9 2 5 1 4 1 1 6 a 2 0 0 0 e 3 1 " , " g e n d e r " : 2 , " i d " : 1 6 9 0 9 2 6 , " n a m e " : " m a r k c h i u " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " e n o r m o u s p r i s o n e r " , " c r e d i t _ i d " : " 5 5 c b 7 d 1 c 9 2 5 1 4 1 7 6 3 e 0 0 0 1 0 a " , " g e n d e r " : 0 , " i d " : 9 9 8 5 0 1 , " n a m e " : " t u r b o k o n g " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " c h i n e s e p o l i c e o f f i c e r " , " c r e d i t _ i d " : " 5 5 c b 7 d 4 2 9 2 5 1 4 1 7 6 4 5 0 0 0 1 2 3 " , " g e n d e r " : 2 , " i d " : 6 2 9 3 7 , " n a m e " : " s a i - k i t y u n g " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " c h i n e s e p o l i c e o f f i c e r " , " c r e d i t _ i d " : " 5 5 c b 7 d 5 8 c 3 a 3 6 8 5 7 0 1 0 0 0 0 e a " , " g e n d e r " : 2 , " i d " : 2 1 1 5 8 6 , " n a m e " : " c h i k e c h a n " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 1 6 5 , " c h a r a c t e r " : " s t o c k y c h i n e s e m a n " , " c r e d i t _ i d " : " 5 7 f a 0 e b d c 3 a 3 6 8 1 a 2 9 0 0 5 5 4 9 " , " g e n d e r " : 2 , " i d " : 1 6 4 6 7 0 1 , " n a m e " : " j a m i e h a y d e n " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " j u m p y t h u g " , " c r e d i t _ i d " : " 5 5 c b 7 d a b 9 2 5 1 4 1 7 6 4 5 0 0 0 1 2 8 " , " g e n d e r " : 2 , " i d " : 9 3 2 1 1 , " n a m e " : " d a v i d m u r r a y " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " d o c k t h u g " , " c r e d i t _ i d " : " 5 5 c b 7 d f 6 9 2 5 1 4 1 7 6 4 f 0 0 0 0 e c " , " g e n d e r " : 2 , " i d " : 5 5 6 4 4 5 , " n a m e " : " d a r r a g h k e l l y " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 1 6 6 , " c h a r a c t e r " : " d o c k t h u g " , " c r e d i t _ i d " : " 5 7 f a 1 0 0 9 9 2 5 1 4 1 2 0 c 5 0 0 5 2 b 6 " , " g e n d e r " : 2 , " i d " : 1 6 0 2 3 7 0 , " n a m e " : " j o h n k a z e k " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 1 6 7 , " c h a r a c t e r " : " d o c k c o p " , " c r e d i t _ i d " : " 5 7 f a 1 4 0 a c 3 a 3 6 8 6 f f f 0 0 6 c 3 6 " , " g e n d e r " : 2 , " i d " : 5 4 1 5 , " n a m e " : " j o s e p h r y e " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 1 6 8 , " c h a r a c t e r " : " d o c k c o p " , " c r e d i t _ i d " : " 5 7 f a 1 5 0 0 c 3 a 3 6 8 1 b 8 f 0 0 5 0 4 7 " , " g e n d e r " : 2 , " i d " : 1 6 9 1 8 7 5 , " n a m e " : " k w a k u a n k o m a h " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 1 6 9 , " c h a r a c t e r " : " p o l i c e p r i s o n o f f i c i a l " , " c r e d i t _ i d " : " 5 7 f a 1 6 8 9 c 3 a 3 6 8 1 b f f 0 0 5 1 5 3 " , " g e n d e r " : 1 , " i d " : 1 6 9 1 8 7 6 , " n a m e " : " j o m a r t i n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " w a y n e e n t e r p r i s e s e x e c u t i v e " , " c r e d i t _ i d " : " 5 5 c b 7 e 4 5 9 2 5 1 4 1 7 6 4 f 0 0 0 0 f 3 " , " g e n d e r " : 2 , " i d " : 2 8 1 5 2 7 , " n a m e " : " c h a r l e s e d w a r d s " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " f e m a l e r e s t a u r a n t g u e s t " , " c r e d i t _ i d " : " 5 5 c b 7 e 5 a 9 2 5 1 4 1 7 6 4 5 0 0 0 1 3 f " , " g e n d e r " : 0 , " i d " : 2 8 7 4 9 , " n a m e " : " l u c y r u s s e l l " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 1 8 8 , " c h a r a c t e r " : " m a l e r e s t a u r a n t g u e s t " , " c r e d i t _ i d " : " 5 8 0 4 f 2 9 3 c 3 a 3 6 8 6 1 0 c 0 0 0 d 0 9 " , " g e n d e r " : 2 , " i d " : 1 6 9 5 9 5 9 , " n a m e " : " m a r k s t r a k e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 1 7 0 , " c h a r a c t e r " : " m a l e r e s t a u r a n t g u e s t " , " c r e d i t _ i d " : " 5 7 f a 1 c 7 c 9 2 5 1 4 1 2 0 c 5 0 0 5 9 6 e " , " g e n d e r " : 2 , " i d " : 1 6 9 1 8 8 7 , " n a m e " : " t i m o t h y d e e n i h a n " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 1 7 1 , " c h a r a c t e r " : " r e s t a u r a n t b l o n d e # 1 " , " c r e d i t _ i d " : " 5 7 f a 1 e f 4 9 2 5 1 4 1 2 0 f 9 0 0 5 e 5 6 " , " g e n d e r " : 1 , " i d " : 1 6 9 1 8 9 2 , " n a m e " : " f l a v i a m a s e t t o " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 1 7 2 , " c h a r a c t e r " : " r e s t a u r a n t b l o n d e # 2 " , " c r e d i t _ i d " : " 5 7 f a 1 f 8 3 9 2 5 1 4 1 1 f d 3 0 0 5 e 1 f " , " g e n d e r " : 1 , " i d " : 1 6 9 1 8 9 5 , " n a m e " : " e m i l y s t e v e n - d a l y " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " m a i t r e d " , " c r e d i t _ i d " : " 5 5 c b 7 e 7 1 9 2 5 1 4 1 7 6 4 b 0 0 0 1 2 f " , " g e n d e r " : 2 , " i d " : 1 4 6 1 4 0 , " n a m e " : " d a v i d b e d e l l a " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " g o t h a m d o c k e m p l o y e e " , " c r e d i t _ i d " : " 5 5 c b 7 e d 4 c 3 a 3 6 8 5 6 f 6 0 0 0 1 0 6 " , " g e n d e r " : 2 , " i d " : 3 6 9 0 1 , " n a m e " : " m a r t i n m c d o u g a l l " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 1 7 3 , " c h a r a c t e r " : " a r k h a m t h u g # 1 " , " c r e d i t _ i d " : " 5 7 f a 2 1 8 e c 3 a 3 6 8 1 a 2 9 0 0 6 0 8 d " , " g e n d e r " : 2 , " i d " : 2 9 6 1 5 , " n a m e " : " n o a h l e e m a r g e t t s " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 1 7 4 , " c h a r a c t e r " : " a r k h a m t h u g # 2 " , " c r e d i t _ i d " : " 5 7 f b 3 e 2 7 9 2 5 1 4 1 4 4 a c 0 0 6 1 0 6 " , " g e n d e r " : 2 , " i d " : 1 2 3 3 8 1 9 , " n a m e " : " j o e h a n l e y " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 1 7 5 , " c h a r a c t e r " : " a r k h a m t h u g # 3 " , " c r e d i t _ i d " : " 5 7 f b 4 2 1 f c 3 a 3 6 8 3 a c 9 0 0 5 e 5 1 " , " g e n d e r " : 2 , " i d " : 1 5 9 2 2 1 6 , " n a m e " : " k a r l s h i e l s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " a r k h a m u n i f o r m e d p o l i c e m a n " , " c r e d i t _ i d " : " 5 5 c b 7 e f 1 c 3 a 3 6 8 5 7 0 1 0 0 0 1 1 7 " , " g e n d e r " : 2 , " i d " : 1 2 2 5 3 5 7 , " n a m e " : " r o g e r g r i f f i t h s " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " a r k h a m l u n a t i c " , " c r e d i t _ i d " : " 5 5 c b 7 f 0 b 9 2 5 1 4 1 7 6 4 b 0 0 0 1 3 6 " , " g e n d e r " : 2 , " i d " : 3 9 6 8 1 , " n a m e " : " s t e p h e n w a l t e r s " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " a r k h a m c h a s e c o p " , " c r e d i t _ i d " : " 5 5 c b 7 f 2 4 c 3 a 3 6 8 5 6 f b 0 0 0 1 2 a " , " g e n d e r " : 2 , " i d " : 4 0 6 8 7 , " n a m e " : " r i c h a r d l a i n g " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " g o t h a m c a r c o p " , " c r e d i t _ i d " : " 5 5 c b 7 f 4 c 9 2 5 1 4 1 7 6 3 9 0 0 0 1 3 7 " , " g e n d e r " : 2 , " i d " : 2 7 7 0 9 , " n a m e " : " m a t t m i l l e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " c a p t a i n s i m o n s o n " , " c r e d i t _ i d " : " 5 5 c b 7 f 6 5 c 3 a 3 6 8 5 6 f e 0 0 0 1 5 b " , " g e n d e r " : 2 , " i d " : 1 3 6 2 1 1 8 , " n a m e " : " r i s t e a r d c o o p e r " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " o l d e r g o t h a m w a t e r b o a r d t e c h n i c i a n " , " c r e d i t _ i d " : " 5 5 c b 7 f 7 a c 3 a 3 6 8 5 6 f 9 0 0 0 1 3 5 " , " g e n d e r " : 2 , " i d " : 1 0 6 5 7 , " n a m e " : " s h a n e r i m m e r " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " y o u n g e r g o t h a m w a t e r b o a r d t e c h n i c i a n " , " c r e d i t _ i d " : " 5 5 c b 7 f 9 4 c 3 a 3 6 8 5 7 0 4 0 0 0 1 b 1 " , " g e n d e r " : 2 , " i d " : 7 0 2 3 0 , " n a m e " : " j e r e m y t h e o b a l d " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " g o t h a m s o c i e t y d a m e " , " c r e d i t _ i d " : " 5 5 c b 7 f b 3 9 2 5 1 4 1 7 6 4 b 0 0 0 1 4 5 " , " g e n d e r " : 1 , " i d " : 1 0 5 1 5 9 , " n a m e " : " a l e x a n d r a b a s t e d o " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 1 4 1 , " c h a r a c t e r " : " n a r r o w s b r i d g e c o p " , " c r e d i t _ i d " : " 5 7 3 f 2 1 a 7 9 2 5 1 4 1 6 b e 1 0 0 0 b 0 7 " , " g e n d e r " : 2 , " i d " : 1 2 2 6 7 0 7 , " n a m e " : " j o h n j u d d " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 1 7 6 , " c h a r a c t e r " : " f a r m e r " , " c r e d i t _ i d " : " 5 7 f b 4 6 6 c c 3 a 3 6 8 3 7 9 6 0 0 6 1 a 7 " , " g e n d e r " : 0 , " i d " : 1 6 9 2 4 1 6 , " n a m e " : " s o o h e e d i n g " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 1 7 7 , " c h a r a c t e r " : " t r a n

In [191]:
print(new_df[new_df['title'] == 'Batman Begins']['tags'].values[0])

driven by tragedy, billionair bruce wayn dedic hi life to uncov and defeat the corrupt that plagu hi home, gotham city. unabl to work within the system, he instead creat a new identity, a symbol of fear for the crimin underworld - the batman. [ { " i d " : 2 8 , " n a m e " : " a c t i o n " } , { " i d " : 8 0 , " n a m e " : " c r i m e " } , { " i d " : 1 8 , " n a m e " : " d r a m a " } ] [ { " i d " : 4 8 6 , " n a m e " : " h i m a l a y a " } , { " i d " : 7 7 9 , " n a m e " : " m a r t i a l a r t s " } , { " i d " : 8 4 9 , " n a m e " : " d c c o m i c s " } , { " i d " : 8 5 3 , " n a m e " : " c r i m e f i g h t e r " } , { " i d " : 1 3 0 8 , " n a m e " : " s e c r e t i d e n t i t y " } , { " i d " : 1 5 6 8 , " n a m e " : " u n d e r c o v e r " } , { " i d " : 1 7 0 1 , " n a m e " : " h e r o " } , { " i d " : 1 8 7 2 , " n a m e " : " l o s s o f f a t h e r " } , { " i d " : 3 6 7 9 , " n a m e " : " s o c i e t y " } , { " i d " : 6 9 6 9 , " n a m e " : " g o t h a m c i t y " } , { " i d " : 7 0 0 2 , " n a m e " : " v i g i l a n t e " } , { " i d " : 9 7 1 5 , " n a m e " : " s u p e r h e r o " } , { " i d " : 9 7 1 7 , " n a m e " : " b a s e d o n c o m i c b o o k " } , { " i d " : 9 8 2 3 , " n a m e " : " r i v a l r y " } , { " i d " : 1 0 0 4 4 , " n a m e " : " t r a g i c h e r o " } , { " i d " : 1 0 2 7 8 , " n a m e " : " n i n j a " } , { " i d " : 1 0 8 4 2 , " n a m e " : " g o o d v s e v i l " } , { " i d " : 1 4 5 3 6 , " n a m e " : " c r i m e " } , { " i d " : 1 6 3 4 5 5 , " n a m e " : " s u p e r p o w e r s " } , { " i d " : 1 7 3 7 1 9 , " n a m e " : " h a u n t e d b y t h e p a s t " } , { " i d " : 1 7 9 0 9 5 , " n a m e " : " e v i l d o c t o r " } , { " i d " : 1 8 7 7 1 0 , " n a m e " : " e s c a p a d e " } , { " i d " : 2 0 6 6 9 4 , " n a m e " : " m a s t e r v i l l a i n " } , { " i d " : 2 0 6 7 0 0 , " n a m e " : " f i g h t i n g c r i m e " } , { " i d " : 2 0 6 7 0 9 , " n a m e " : " u n f u l f i l l m e n t " } , { " i d " : 2 0 6 7 1 5 , " n a m e " : " l o v e a n d r o m a n c e " } , { " i d " : 2 0 6 7 1 6 , " n a m e " : " u n f u l f i l l e d l o v e " } ] [ { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " b r u c e w a y n e / b a t m a n " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 3 d " , " g e n d e r " : 2 , " i d " : 3 8 9 4 , " n a m e " : " c h r i s t i a n b a l e " , " o r d e r " : 0 } , { " c a s t _ i d " : 1 4 , " c h a r a c t e r " : " a l f r e d p e n n y w o r t h " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 4 1 " , " g e n d e r " : 2 , " i d " : 3 8 9 5 , " n a m e " : " m i c h a e l c a i n e " , " o r d e r " : 1 } , { " c a s t _ i d " : 1 5 , " c h a r a c t e r " : " h e n r i d u c a r d " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 4 5 " , " g e n d e r " : 2 , " i d " : 3 8 9 6 , " n a m e " : " l i a m n e e s o n " , " o r d e r " : 2 } , { " c a s t _ i d " : 1 6 , " c h a r a c t e r " : " r a c h e l d a w e s " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 4 9 " , " g e n d e r " : 1 , " i d " : 3 8 9 7 , " n a m e " : " k a t i e h o l m e s " , " o r d e r " : 3 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " j i m g o r d o n " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 3 5 " , " g e n d e r " : 2 , " i d " : 6 4 , " n a m e " : " g a r y o l d m a n " , " o r d e r " : 4 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " d r . j o n a t h a n c r a n e / s c a r e c r o w " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 3 9 " , " g e n d e r " : 2 , " i d " : 2 0 3 7 , " n a m e " : " c i l l i a n m u r p h y " , " o r d e r " : 5 } , { " c a s t _ i d " : 2 9 , " c h a r a c t e r " : " c a r m i n e f a l c o n e " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 1 " , " g e n d e r " : 2 , " i d " : 2 0 7 , " n a m e " : " t o m w i l k i n s o n " , " o r d e r " : 6 } , { " c a s t _ i d " : 3 1 , " c h a r a c t e r " : " l u c i u s f o x " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 5 " , " g e n d e r " : 2 , " i d " : 1 9 2 , " n a m e " : " m o r g a n f r e e m a n " , " o r d e r " : 7 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " e a r l e " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 9 " , " g e n d e r " : 2 , " i d " : 5 8 5 , " n a m e " : " r u t g e r h a u e r " , " o r d e r " : 8 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " r a ' s a l g h u l " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 7 d " , " g e n d e r " : 2 , " i d " : 3 8 9 9 , " n a m e " : " k e n w a t a n a b e " , " o r d e r " : 9 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " f l a s s " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 1 " , " g e n d e r " : 2 , " i d " : 5 3 4 , " n a m e " : " m a r k b o o n e j u n i o r " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " t h o m a s w a y n e " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 5 " , " g e n d e r " : 2 , " i d " : 3 9 0 0 , " n a m e " : " l i n u s r o a c h e " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " f i n c h " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 9 " , " g e n d e r " : 2 , " i d " : 5 4 4 , " n a m e " : " l a r r y h o l d e n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " j u d g e f a d e n " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 8 d " , " g e n d e r " : 0 , " i d " : 1 5 1 9 4 3 , " n a m e " : " g e r a r d m u r p h y " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " l o e b " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 9 1 " , " g e n d e r " : 2 , " i d " : 1 2 8 3 8 6 , " n a m e " : " c o l i n m c f a r l a n e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " l i t t l e b o y " , " c r e d i t _ i d " : " 5 2 f e 4 2 3 0 c 3 a 3 6 8 4 7 f 8 0 0 a c 9 5 " , " g e n d e r " : 2 , " i d " : 4 8 9 4 6 7 , " n a m e " : " j a c k g l e e s o n " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " c r a n e t h u g # 1 " , " c r e d i t _ i d " : " 5 3 6 a 3 1 8 7 0 e 0 a 2 6 4 7 c 4 0 0 a 1 4 d " , " g e n d e r " : 0 , " i d " : 1 3 1 7 3 9 7 , " n a m e " : " t . j . r a m i n i " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 1 8 9 , " c h a r a c t e r " : " c r a n e t h u g # 2 " , " c r e d i t _ i d " : " 5 8 0 4 f 4 1 4 c 3 a 3 6 8 6 a 3 4 0 0 0 9 7 a " , " g e n d e r " : 2 , " i d " : 1 6 9 5 9 6 0 , " n a m e " : " k i e r a n h u r l e y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " b l o n d e f e m a l e r e p o r t e r / a s s a s s i n " , " c r e d i t _ i d " : " 5 3 a a 4 d 4 a c 3 a 3 6 8 4 c f b 0 0 0 d 9 3 " , " g e n d e r " : 0 , " i d " : 1 3 3 4 1 2 4 , " n a m e " : " c a t h e r i n e p o r t e r " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " b r u c e w a y n e a l s k i n d " , " c r e d i t _ i d " : " 5 4 e 2 7 d e 7 c 3 a 3 6 8 0 8 7 b 0 0 2 3 d d " , " g e n d e r " : 2 , " i d " : 1 1 7 2 3 7 1 , " n a m e " : " g u s l e w i s " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " h o m e l e s s m a n " , " c r e d i t _ i d " : " 5 5 5 c 3 2 d 4 9 2 5 1 4 1 6 b 5 d 0 0 0 a 2 0 " , " g e n d e r " : 2 , " i d " : 1 1 1 8 , " n a m e " : " r a d e s e r b e d z i j a " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " m a r t h a w a y n e " , " c r e d i t _ i d " : " 5 5 c b 7 b 9 3 9 2 5 1 4 1 7 6 4 8 0 0 0 0 a 3 " , " g e n d e r " : 1 , " i d " : 3 9 0 2 , " n a m e " : " s a r a s t e w a r t " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " j o e c h i l l " , " c r e d i t _ i d " : " 5 5 c b 7 b d 0 9 2 5 1 4 1 7 6 4 5 0 0 0 0 f 8 " , " g e n d e r " : 2 , " i d " : 3 9 0 1 , " n a m e " : " r i c h a r d b r a k e " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " r a c h e l d a w e s - a g e 8 " , " c r e d i t _ i d " : " 5 5 c b 7 b f 5 9 2 5 1 4 1 7 6 4 f 0 0 0 0 c 6 " , " g e n d e r " : 1 , " i d " : 7 8 1 1 4 , " n a m e " : " e m m a l o c k h a r t " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " j e s s i c a " , " c r e d i t _ i d " : " 5 5 c b 7 c 2 2 c 3 a 3 6 8 5 6 f 9 0 0 0 0 d 7 " , " g e n d e r " : 1 , " i d " : 8 7 1 9 4 , " n a m e " : " c h r i s t i n e a d a m s " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " f r e d e r i c k s " , " c r e d i t _ i d " : " 5 5 c b 7 c 4 0 c 3 a 3 6 8 5 6 f b 0 0 0 0 e e " , " g e n d e r " : 2 , " i d " : 7 0 2 2 5 , " n a m e " : " j o h n n o l a n " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " c o u r t h o u s e r e p o r t e r # 1 " , " c r e d i t _ i d " : " 5 5 c b 7 c 6 8 9 2 5 1 4 1 7 6 4 b 0 0 0 1 0 7 " , " g e n d e r " : 1 , " i d " : 7 9 1 2 4 , " n a m e " : " k a r e n d a v i d " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 1 6 1 , " c h a r a c t e r " : " c o u r t h o u s e r e p o r t e r # 2 " , " c r e d i t _ i d " : " 5 7 f 7 b b 6 f c 3 a 3 6 8 3 a a 7 0 0 2 9 4 f " , " g e n d e r " : 2 , " i d " : 1 6 9 0 7 7 3 , " n a m e " : " j o n a t h a n d . e l l i s " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " f a d e n ' s l i m o d r i v e r " , " c r e d i t _ i d " : " 5 5 c b 7 c a 9 c 3 a 3 6 8 5 7 0 8 0 0 0 0 d 3 " , " g e n d e r " : 2 , " i d " : 3 9 6 6 0 , " n a m e " : " t a m e r h a s s a n " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " u n i f o r m e d p o l i c e m a n # 1 " , " c r e d i t _ i d " : " 5 5 c b 7 c b f c 3 a 3 6 8 5 7 0 4 0 0 0 1 7 4 " , " g e n d e r " : 2 , " i d " : 5 5 9 2 0 9 , " n a m e " : " r o n a n l e a h y " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " o l d a s i a n p r i s o n e r " , " c r e d i t _ i d " : " 5 5 c b 7 c d b c 3 a 3 6 8 5 6 f e 0 0 0 1 2 7 " , " g e n d e r " : 2 , " i d " : 1 2 5 7 8 2 1 , " n a m e " : " v i n c e n t w o n g " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " b h u t a n e s e p r i s o n g u a r d # 1 " , " c r e d i t _ i d " : " 5 5 c b 7 c f 2 9 2 5 1 4 1 7 6 3 9 0 0 0 1 0 4 " , " g e n d e r " : 2 , " i d " : 6 7 2 1 2 , " n a m e " : " t o m w u " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 1 6 2 , " c h a r a c t e r " : " b h u t a n e s e p r i s o n g u a r d # 2 " , " c r e d i t _ i d " : " 5 7 f 8 0 3 c 2 9 2 5 1 4 1 1 6 a 2 0 0 0 e 3 1 " , " g e n d e r " : 2 , " i d " : 1 6 9 0 9 2 6 , " n a m e " : " m a r k c h i u " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " e n o r m o u s p r i s o n e r " , " c r e d i t _ i d " : " 5 5 c b 7 d 1 c 9 2 5 1 4 1 7 6 3 e 0 0 0 1 0 a " , " g e n d e r " : 0 , " i d " : 9 9 8 5 0 1 , " n a m e " : " t u r b o k o n g " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " c h i n e s e p o l i c e o f f i c e r " , " c r e d i t _ i d " : " 5 5 c b 7 d 4 2 9 2 5 1 4 1 7 6 4 5 0 0 0 1 2 3 " , " g e n d e r " : 2 , " i d " : 6 2 9 3 7 , " n a m e " : " s a i - k i t y u n g " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " c h i n e s e p o l i c e o f f i c e r " , " c r e d i t _ i d " : " 5 5 c b 7 d 5 8 c 3 a 3 6 8 5 7 0 1 0 0 0 0 e a " , " g e n d e r " : 2 , " i d " : 2 1 1 5 8 6 , " n a m e " : " c h i k e c h a n " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 1 6 5 , " c h a r a c t e r " : " s t o c k y c h i n e s e m a n " , " c r e d i t _ i d " : " 5 7 f a 0 e b d c 3 a 3 6 8 1 a 2 9 0 0 5 5 4 9 " , " g e n d e r " : 2 , " i d " : 1 6 4 6 7 0 1 , " n a m e " : " j a m i e h a y d e n " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " j u m p y t h u g " , " c r e d i t _ i d " : " 5 5 c b 7 d a b 9 2 5 1 4 1 7 6 4 5 0 0 0 1 2 8 " , " g e n d e r " : 2 , " i d " : 9 3 2 1 1 , " n a m e " : " d a v i d m u r r a y " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " d o c k t h u g " , " c r e d i t _ i d " : " 5 5 c b 7 d f 6 9 2 5 1 4 1 7 6 4 f 0 0 0 0 e c " , " g e n d e r " : 2 , " i d " : 5 5 6 4 4 5 , " n a m e " : " d a r r a g h k e l l y " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 1 6 6 , " c h a r a c t e r " : " d o c k t h u g " , " c r e d i t _ i d " : " 5 7 f a 1 0 0 9 9 2 5 1 4 1 2 0 c 5 0 0 5 2 b 6 " , " g e n d e r " : 2 , " i d " : 1 6 0 2 3 7 0 , " n a m e " : " j o h n k a z e k " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 1 6 7 , " c h a r a c t e r " : " d o c k c o p " , " c r e d i t _ i d " : " 5 7 f a 1 4 0 a c 3 a 3 6 8 6 f f f 0 0 6 c 3 6 " , " g e n d e r " : 2 , " i d " : 5 4 1 5 , " n a m e " : " j o s e p h r y e " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 1 6 8 , " c h a r a c t e r " : " d o c k c o p " , " c r e d i t _ i d " : " 5 7 f a 1 5 0 0 c 3 a 3 6 8 1 b 8 f 0 0 5 0 4 7 " , " g e n d e r " : 2 , " i d " : 1 6 9 1 8 7 5 , " n a m e " : " k w a k u a n k o m a h " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 1 6 9 , " c h a r a c t e r " : " p o l i c e p r i s o n o f f i c i a l " , " c r e d i t _ i d " : " 5 7 f a 1 6 8 9 c 3 a 3 6 8 1 b f f 0 0 5 1 5 3 " , " g e n d e r " : 1 , " i d " : 1 6 9 1 8 7 6 , " n a m e " : " j o m a r t i n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " w a y n e e n t e r p r i s e s e x e c u t i v e " , " c r e d i t _ i d " : " 5 5 c b 7 e 4 5 9 2 5 1 4 1 7 6 4 f 0 0 0 0 f 3 " , " g e n d e r " : 2 , " i d " : 2 8 1 5 2 7 , " n a m e " : " c h a r l e s e d w a r d s " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " f e m a l e r e s t a u r a n t g u e s t " , " c r e d i t _ i d " : " 5 5 c b 7 e 5 a 9 2 5 1 4 1 7 6 4 5 0 0 0 1 3 f " , " g e n d e r " : 0 , " i d " : 2 8 7 4 9 , " n a m e " : " l u c y r u s s e l l " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 1 8 8 , " c h a r a c t e r " : " m a l e r e s t a u r a n t g u e s t " , " c r e d i t _ i d " : " 5 8 0 4 f 2 9 3 c 3 a 3 6 8 6 1 0 c 0 0 0 d 0 9 " , " g e n d e r " : 2 , " i d " : 1 6 9 5 9 5 9 , " n a m e " : " m a r k s t r a k e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 1 7 0 , " c h a r a c t e r " : " m a l e r e s t a u r a n t g u e s t " , " c r e d i t _ i d " : " 5 7 f a 1 c 7 c 9 2 5 1 4 1 2 0 c 5 0 0 5 9 6 e " , " g e n d e r " : 2 , " i d " : 1 6 9 1 8 8 7 , " n a m e " : " t i m o t h y d e e n i h a n " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 1 7 1 , " c h a r a c t e r " : " r e s t a u r a n t b l o n d e # 1 " , " c r e d i t _ i d " : " 5 7 f a 1 e f 4 9 2 5 1 4 1 2 0 f 9 0 0 5 e 5 6 " , " g e n d e r " : 1 , " i d " : 1 6 9 1 8 9 2 , " n a m e " : " f l a v i a m a s e t t o " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 1 7 2 , " c h a r a c t e r " : " r e s t a u r a n t b l o n d e # 2 " , " c r e d i t _ i d " : " 5 7 f a 1 f 8 3 9 2 5 1 4 1 1 f d 3 0 0 5 e 1 f " , " g e n d e r " : 1 , " i d " : 1 6 9 1 8 9 5 , " n a m e " : " e m i l y s t e v e n - d a l y " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " m a i t r e d " , " c r e d i t _ i d " : " 5 5 c b 7 e 7 1 9 2 5 1 4 1 7 6 4 b 0 0 0 1 2 f " , " g e n d e r " : 2 , " i d " : 1 4 6 1 4 0 , " n a m e " : " d a v i d b e d e l l a " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " g o t h a m d o c k e m p l o y e e " , " c r e d i t _ i d " : " 5 5 c b 7 e d 4 c 3 a 3 6 8 5 6 f 6 0 0 0 1 0 6 " , " g e n d e r " : 2 , " i d " : 3 6 9 0 1 , " n a m e " : " m a r t i n m c d o u g a l l " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 1 7 3 , " c h a r a c t e r " : " a r k h a m t h u g # 1 " , " c r e d i t _ i d " : " 5 7 f a 2 1 8 e c 3 a 3 6 8 1 a 2 9 0 0 6 0 8 d " , " g e n d e r " : 2 , " i d " : 2 9 6 1 5 , " n a m e " : " n o a h l e e m a r g e t t s " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 1 7 4 , " c h a r a c t e r " : " a r k h a m t h u g # 2 " , " c r e d i t _ i d " : " 5 7 f b 3 e 2 7 9 2 5 1 4 1 4 4 a c 0 0 6 1 0 6 " , " g e n d e r " : 2 , " i d " : 1 2 3 3 8 1 9 , " n a m e " : " j o e h a n l e y " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 1 7 5 , " c h a r a c t e r " : " a r k h a m t h u g # 3 " , " c r e d i t _ i d " : " 5 7 f b 4 2 1 f c 3 a 3 6 8 3 a c 9 0 0 5 e 5 1 " , " g e n d e r " : 2 , " i d " : 1 5 9 2 2 1 6 , " n a m e " : " k a r l s h i e l s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " a r k h a m u n i f o r m e d p o l i c e m a n " , " c r e d i t _ i d " : " 5 5 c b 7 e f 1 c 3 a 3 6 8 5 7 0 1 0 0 0 1 1 7 " , " g e n d e r " : 2 , " i d " : 1 2 2 5 3 5 7 , " n a m e " : " r o g e r g r i f f i t h s " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " a r k h a m l u n a t i c " , " c r e d i t _ i d " : " 5 5 c b 7 f 0 b 9 2 5 1 4 1 7 6 4 b 0 0 0 1 3 6 " , " g e n d e r " : 2 , " i d " : 3 9 6 8 1 , " n a m e " : " s t e p h e n w a l t e r s " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " a r k h a m c h a s e c o p " , " c r e d i t _ i d " : " 5 5 c b 7 f 2 4 c 3 a 3 6 8 5 6 f b 0 0 0 1 2 a " , " g e n d e r " : 2 , " i d " : 4 0 6 8 7 , " n a m e " : " r i c h a r d l a i n g " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " g o t h a m c a r c o p " , " c r e d i t _ i d " : " 5 5 c b 7 f 4 c 9 2 5 1 4 1 7 6 3 9 0 0 0 1 3 7 " , " g e n d e r " : 2 , " i d " : 2 7 7 0 9 , " n a m e " : " m a t t m i l l e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " c a p t a i n s i m o n s o n " , " c r e d i t _ i d " : " 5 5 c b 7 f 6 5 c 3 a 3 6 8 5 6 f e 0 0 0 1 5 b " , " g e n d e r " : 2 , " i d " : 1 3 6 2 1 1 8 , " n a m e " : " r i s t e a r d c o o p e r " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " o l d e r g o t h a m w a t e r b o a r d t e c h n i c i a n " , " c r e d i t _ i d " : " 5 5 c b 7 f 7 a c 3 a 3 6 8 5 6 f 9 0 0 0 1 3 5 " , " g e n d e r " : 2 , " i d " : 1 0 6 5 7 , " n a m e " : " s h a n e r i m m e r " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " y o u n g e r g o t h a m w a t e r b o a r d t e c h n i c i a n " , " c r e d i t _ i d " : " 5 5 c b 7 f 9 4 c 3 a 3 6 8 5 7 0 4 0 0 0 1 b 1 " , " g e n d e r " : 2 , " i d " : 7 0 2 3 0 , " n a m e " : " j e r e m y t h e o b a l d " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " g o t h a m s o c i e t y d a m e " , " c r e d i t _ i d " : " 5 5 c b 7 f b 3 9 2 5 1 4 1 7 6 4 b 0 0 0 1 4 5 " , " g e n d e r " : 1 , " i d " : 1 0 5 1 5 9 , " n a m e " : " a l e x a n d r a b a s t e d o " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 1 4 1 , " c h a r a c t e r " : " n a r r o w s b r i d g e c o p " , " c r e d i t _ i d " : " 5 7 3 f 2 1 a 7 9 2 5 1 4 1 6 b e 1 0 0 0 b 0 7 " , " g e n d e r " : 2 , " i d " : 1 2 2 6 7 0 7 , " n a m e " : " j o h n j u d d " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 1 7 6 , " c h a r a c t e r " : " f a r m e r " , " c r e d i t _ i d " : " 5 7 f b 4 6 6 c c 3 a 3 6 8 3 7 9 6 0 0 6 1 a 7 " , " g e n d e r " : 0 , " i d " : 1 6 9 2 4 1 6 , " n a m e " : " s o o h e e d i n g " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 1 7 7 , " c h a r a c t e r " : " t r a n

In [192]:
print(new_df[new_df['title'] == 'The Dark Knight']['tags'].values[0])

batman rais the stake in hi war on crime. with the help of lt. jim gordon and district attorney harvey dent, batman set out to dismantl the remain crimin organ that plagu the streets. the partnership prove to be effective, but they soon find themselv prey to a reign of chao unleash by a rise crimin mastermind known to the terrifi citizen of gotham as the joker. [ { " i d " : 1 8 , " n a m e " : " d r a m a " } , { " i d " : 2 8 , " n a m e " : " a c t i o n " } , { " i d " : 8 0 , " n a m e " : " c r i m e " } , { " i d " : 5 3 , " n a m e " : " t h r i l l e r " } ] [ { " i d " : 8 4 9 , " n a m e " : " d c c o m i c s " } , { " i d " : 8 5 3 , " n a m e " : " c r i m e f i g h t e r " } , { " i d " : 1 3 0 8 , " n a m e " : " s e c r e t i d e n t i t y " } , { " i d " : 3 1 5 1 , " n a m e " : " s c a r e c r o w " } , { " i d " : 4 4 2 6 , " n a m e " : " s a d i s m " } , { " i d " : 4 6 3 0 , " n a m e " : " c h a o s " } , { " i d " : 6 9 6 9 , " n a m e " : " g o t h a m c i t y " } , { " i d " : 7 0 0 2 , " n a m e " : " v i g i l a n t e " } , { " i d " : 9 5 3 7 , " n a m e " : " j o k e r " } , { " i d " : 9 7 1 5 , " n a m e " : " s u p e r h e r o " } , { " i d " : 9 7 1 7 , " n a m e " : " b a s e d o n c o m i c b o o k " } , { " i d " : 1 0 0 4 4 , " n a m e " : " t r a g i c h e r o " } , { " i d " : 1 0 2 9 1 , " n a m e " : " o r g a n i z e d c r i m e " } , { " i d " : 1 8 0 2 3 , " n a m e " : " c r i m i n a l m a s t e r m i n d " } , { " i d " : 3 3 5 1 8 , " n a m e " : " d i s t r i c t a t t o r n e y " } , { " i d " : 1 5 6 3 9 5 , " n a m e " : " i m a x " } , { " i d " : 1 6 3 0 7 4 , " n a m e " : " s u p e r v i l l a i n " } , { " i d " : 1 6 3 4 5 5 , " n a m e " : " s u p e r p o w e r s " } , { " i d " : 2 3 0 7 7 5 , " n a m e " : " b a t m a n " } ] [ { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " b r u c e w a y n e " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 1 7 " , " g e n d e r " : 2 , " i d " : 3 8 9 4 , " n a m e " : " c h r i s t i a n b a l e " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " j o k e r " , " c r e d i t _ i d " : " 5 2 f e 4 2 1 f c 3 a 3 6 8 4 7 f 8 0 0 5 c b f " , " g e n d e r " : 2 , " i d " : 1 8 1 0 , " n a m e " : " h e a t h l e d g e r " , " o r d e r " : 1 } , { " c a s t _ i d " : 1 5 , " c h a r a c t e r " : " h a r v e y d e n t " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 c f 1 " , " g e n d e r " : 2 , " i d " : 6 3 8 3 , " n a m e " : " a a r o n e c k h a r t " , " o r d e r " : 2 } , { " c a s t _ i d " : 1 7 , " c h a r a c t e r " : " a l f r e d " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 c f 9 " , " g e n d e r " : 2 , " i d " : 3 8 9 5 , " n a m e " : " m i c h a e l c a i n e " , " o r d e r " : 3 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " r a c h e l " , " c r e d i t _ i d " : " 5 2 f e 4 2 1 f c 3 a 3 6 8 4 7 f 8 0 0 5 c d 5 " , " g e n d e r " : 1 , " i d " : 1 5 7 9 , " n a m e " : " m a g g i e g y l l e n h a a l " , " o r d e r " : 4 } , { " c a s t _ i d " : 1 6 , " c h a r a c t e r " : " g o r d o n " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 c f 5 " , " g e n d e r " : 2 , " i d " : 6 4 , " n a m e " : " g a r y o l d m a n " , " o r d e r " : 5 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " l u c i u s f o x " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 1 3 " , " g e n d e r " : 2 , " i d " : 1 9 2 , " n a m e " : " m o r g a n f r e e m a n " , " o r d e r " : 6 } , { " c a s t _ i d " : 2 5 8 , " c h a r a c t e r " : " r a m i r e z " , " c r e d i t _ i d " : " 5 5 d c 9 0 8 3 c 3 a 3 6 8 6 5 7 2 0 0 0 1 9 3 " , " g e n d e r " : 1 , " i d " : 5 3 6 5 1 , " n a m e " : " m o n i q u e g a b r i e l a c u r n e n " , " o r d e r " : 7 } , { " c a s t _ i d " : 2 2 8 , " c h a r a c t e r " : " w u e r t z " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 6 5 " , " g e n d e r " : 2 , " i d " : 5 7 5 9 7 , " n a m e " : " r o n d e a n " , " o r d e r " : 8 } , { " c a s t _ i d " : 2 0 , " c h a r a c t e r " : " s c a r e c r o w " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 c f d " , " g e n d e r " : 2 , " i d " : 2 0 3 7 , " n a m e " : " c i l l i a n m u r p h y " , " o r d e r " : 9 } , { " c a s t _ i d " : 2 2 7 , " c h a r a c t e r " : " l a u " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 6 1 " , " g e n d e r " : 2 , " i d " : 1 0 1 0 1 5 , " n a m e " : " c h i n h a n " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 2 2 5 , " c h a r a c t e r " : " m a y o r " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 5 9 " , " g e n d e r " : 2 , " i d " : 2 1 3 1 6 , " n a m e " : " n e s t o r c a r b o n e l l " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 2 2 9 , " c h a r a c t e r " : " m a r o n i " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 6 9 " , " g e n d e r " : 2 , " i d " : 2 1 3 1 5 , " n a m e " : " e r i c r o b e r t s " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 2 3 2 , " c h a r a c t e r " : " c h e c h e n " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 7 1 " , " g e n d e r " : 2 , " i d " : 1 3 9 3 9 , " n a m e " : " r i t c h i e c o s t e r " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 2 2 4 , " c h a r a c t e r " : " e n g e l " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 5 5 " , " g e n d e r " : 2 , " i d " : 1 9 0 4 , " n a m e " : " a n t h o n y m i c h a e l h a l l " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 2 3 3 , " c h a r a c t e r " : " s t e p h e n s " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 7 5 " , " g e n d e r " : 2 , " i d " : 8 7 9 5 7 , " n a m e " : " k e i t h s z a r a b a j k a " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 2 3 4 , " c h a r a c t e r " : " l o e b " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 7 9 " , " g e n d e r " : 2 , " i d " : 1 2 8 3 8 6 , " n a m e " : " c o l i n m c f a r l a n e " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 2 6 0 , " c h a r a c t e r " : " r e e s e " , " c r e d i t _ i d " : " 5 6 0 c 2 5 0 1 c 3 a 3 6 8 6 8 1 f 0 0 5 b 6 e " , " g e n d e r " : 2 , " i d " : 3 4 5 4 4 , " n a m e " : " j o s h u a h a r t o " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 2 3 0 , " c h a r a c t e r " : " b a r b a r a g o r d o n " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 6 d " , " g e n d e r " : 0 , " i d " : 5 8 6 9 2 , " n a m e " : " m e l i n d a m c g r a w " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 2 6 1 , " c h a r a c t e r " : " j a m e s g o r d o n " , " c r e d i t _ i d " : " 5 6 0 c 2 5 3 4 9 2 5 1 4 1 7 1 9 1 0 0 6 4 b 3 " , " g e n d e r " : 2 , " i d " : 1 8 0 5 2 , " n a m e " : " n a t h a n g a m b l e " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 2 6 2 , " c h a r a c t e r " : " r o s s i " , " c r e d i t _ i d " : " 5 6 0 c 2 5 4 8 9 2 5 1 4 1 5 0 1 9 0 0 0 1 2 f " , " g e n d e r " : 2 , " i d " : 1 0 5 2 8 7 5 , " n a m e " : " m i c h a e l v i e a u " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 2 3 7 , " c h a r a c t e r " : " d o p e y " , " c r e d i t _ i d " : " 5 3 a a 6 3 d e 0 e 0 a 2 6 4 6 d 8 0 0 3 0 b 5 " , " g e n d e r " : 0 , " i d " : 1 1 9 6 1 3 0 , " n a m e " : " m i c h a e l s t o y a n o v " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 2 3 5 , " c h a r a c t e r " : " h a p p y " , " c r e d i t _ i d " : " 5 3 a a 6 2 f 0 0 e 0 a 2 6 4 6 c 2 0 0 1 2 3 8 " , " g e n d e r " : 0 , " i d " : 1 3 3 4 1 3 9 , " n a m e " : " w i l l i a m s m i l l i e " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 2 4 1 , " c h a r a c t e r " : " g a m b o l " , " c r e d i t _ i d " : " 5 5 5 b 4 f c 2 9 2 5 1 4 1 5 8 7 8 0 0 0 a 6 b " , " g e n d e r " : 2 , " i d " : 6 4 8 5 6 , " n a m e " : " m i c h a e l j a i w h i t e " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 2 3 6 , " c h a r a c t e r " : " g r u m p y " , " c r e d i t _ i d " : " 5 3 a a 6 3 a 0 0 e 0 a 2 6 4 6 d 2 0 0 1 1 d 3 " , " g e n d e r " : 2 , " i d " : 1 6 4 7 7 , " n a m e " : " d a n n y g o l d r i n g " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 3 8 5 , " c h a r a c t e r " : " c h u c k l e s " , " c r e d i t _ i d " : " 5 9 9 3 c a d f 9 2 5 1 4 1 5 4 1 2 0 0 c f 4 2 " , " g e n d e r " : 0 , " i d " : 1 2 0 8 9 6 7 , " n a m e " : " m a t t h e w o ' n e i l l " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 2 2 6 , " c h a r a c t e r " : " b a n k m a n a g e r " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 5 d " , " g e n d e r " : 2 , " i d " : 8 8 6 , " n a m e " : " w i l l i a m f i c h t n e r " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 2 6 3 , " c h a r a c t e r " : " d r u g d e a l e r " , " c r e d i t _ i d " : " 5 6 0 c 2 5 b 3 c 3 a 3 6 8 6 8 1 f 0 0 5 b 8 6 " , " g e n d e r " : 0 , " i d " : 1 0 5 6 0 9 0 , " n a m e " : " o l u m i j i o l a w u m i " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 3 8 6 , " c h a r a c t e r " : " d r u g b u y e r " , " c r e d i t _ i d " : " 5 9 9 3 c b 5 4 c 3 a 3 6 8 7 e f f 0 0 c 2 a e " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 0 7 , " n a m e " : " g r e g b e a m " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 3 8 7 , " c h a r a c t e r " : " j u n k i e " , " c r e d i t _ i d " : " 5 9 9 3 c b 6 7 c 3 a 3 6 8 7 e f f 0 0 c 2 d 3 " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 0 8 , " n a m e " : " e r i k h e l l m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 2 3 8 , " c h a r a c t e r " : " n a t a s c h a " , " c r e d i t _ i d " : " 5 3 a a 6 4 6 e 0 e 0 a 2 6 4 6 d 2 0 0 1 1 e c " , " g e n d e r " : 1 , " i d " : 1 0 1 0 1 4 , " n a m e " : " b e a t r i c e r o s e n " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 2 6 4 , " c h a r a c t e r " : " c r i m e b o s s " , " c r e d i t _ i d " : " 5 6 0 c 2 6 1 4 c 3 a 3 6 8 6 8 1 4 0 0 6 9 1 d " , " g e n d e r " : 2 , " i d " : 2 4 5 9 5 , " n a m e " : " v i n c e n z o n i c o l i " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 2 6 5 , " c h a r a c t e r " : " l s i v p " , " c r e d i t _ i d " : " 5 6 0 c 2 6 2 b c 3 a 3 6 8 6 8 0 b 0 0 6 2 2 5 " , " g e n d e r " : 0 , " i d " : 2 0 3 7 2 , " n a m e " : " e d i s o n c h e n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 3 8 8 , " c h a r a c t e r " : " j u d g e s u r r i l l o " , " c r e d i t _ i d " : " 5 9 9 3 c b e 7 c 3 a 3 6 8 7 f 4 6 0 0 c b b b " , " g e n d e r " : 0 , " i d " : 1 5 2 2 0 7 3 , " n a m e " : " n y d i a r o d r i g u e z t e r r a c i n a " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 3 8 9 , " c h a r a c t e r " : " b r i a n " , " c r e d i t _ i d " : " 5 9 9 3 c b f 8 c 3 a 3 6 8 7 e d a 0 0 c 9 1 0 " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 0 9 , " n a m e " : " a n d y l u t h e r " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 3 9 0 , " c h a r a c t e r " : " m a n n o . 1 " , " c r e d i t _ i d " : " 5 9 9 3 c c 1 8 c 3 a 3 6 8 7 f 4 6 0 0 c c 1 0 " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 0 , " n a m e " : " j a m e s f a r r u g g i o " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 3 9 1 , " c h a r a c t e r " : " m a n n o . 2 " , " c r e d i t _ i d " : " 5 9 9 3 c c 2 c c 3 a 3 6 8 7 f 9 e 0 0 d c 3 2 " , " g e n d e r " : 0 , " i d " : 1 8 4 0 4 5 2 , " n a m e " : " t o m m c e l r o y " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 2 6 6 , " c h a r a c t e r " : " a s s i s t a n t d a " , " c r e d i t _ i d " : " 5 6 0 c 2 6 e f c 3 a 3 6 8 6 8 1 4 0 0 6 9 4 8 " , " g e n d e r " : 0 , " i d " : 1 2 2 6 6 9 6 , " n a m e " : " w i l l z a h r n " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 3 9 2 , " c h a r a c t e r " : " t h u g a t p a r t y " , " c r e d i t _ i d " : " 5 9 9 3 c c d 7 c 3 a 3 6 8 7 e d a 0 0 c a 6 e " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 1 , " n a m e " : " j a m e s f i e r r o " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 2 6 7 , " c h a r a c t e r " : " g e n t l e m a n a t p a r t y " , " c r e d i t _ i d " : " 5 6 0 c 2 7 6 6 c 3 a 3 6 8 6 8 1 0 0 0 6 6 2 8 " , " g e n d e r " : 2 , " i d " : 8 5 3 1 9 4 , " n a m e " : " p a t r i c k l e a h y " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 3 9 3 , " c h a r a c t e r " : " m a l e g u e s t " , " c r e d i t _ i d " : " 5 9 9 3 c d 0 4 c 3 a 3 6 8 7 f 8 4 0 0 c e b a " , " g e n d e r " : 0 , " i d " : 1 5 2 6 5 7 4 , " n a m e " : " s a m d e r e n c e " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 3 9 4 , " c h a r a c t e r " : " f e m a l e g u e s t " , " c r e d i t _ i d " : " 5 9 9 3 c d 5 a c 3 a 3 6 8 7 e c 4 0 0 d f 1 1 " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 2 , " n a m e " : " j e n n i f e r k n o x " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 2 6 8 , " c h a r a c t e r " : " j u d g e f r e e l " , " c r e d i t _ i d " : " 5 6 0 c 2 7 b d c 3 a 3 6 8 6 8 1 f 0 0 5 b b b " , " g e n d e r " : 0 , " i d " : 1 4 2 4 0 4 3 , " n a m e " : " p a t r i c k c l e a r " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 2 6 9 , " c h a r a c t e r " : " m a r o n i ' s m i s t r e s s " , " c r e d i t _ i d " : " 5 6 0 c 2 7 d 0 9 2 5 1 4 1 7 e 9 e 0 0 4 5 d 4 " , " g e n d e r " : 1 , " i d " : 1 2 2 0 2 0 1 , " n a m e " : " s a r a h j a y n e d u n n " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 2 7 0 , " c h a r a c t e r " : " g a m b o l ' s b o d y g u a r d ( a s c h u c k y v e n n ) " , " c r e d i t _ i d " : " 5 6 0 c 2 7 e 7 c 3 a 3 6 8 6 8 0 e 0 0 5 f e c " , " g e n d e r " : 0 , " i d " : 1 4 7 8 9 5 , " n a m e " : " c h a r l e s v e n n " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 2 7 1 , " c h a r a c t e r " : " g a m b o l ' s b o d y g u a r d ( a s w i n s t o n e l l i s ) " , " c r e d i t _ i d " : " 5 6 0 c 2 8 4 f 9 2 5 1 4 1 7 1 9 c 0 0 6 1 4 1 " , " g e n d e r " : 0 , " i d " : 1 1 9 5 7 5 8 , " n a m e " : " w i n s t o n g . e l l i s " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 2 2 3 , " c h a r a c t e r " : " j o k e r ' s t h u g " , " c r e d i t _ i d " : " 5 2 f e 4 2 2 0 c 3 a 3 6 8 4 7 f 8 0 0 5 d 5 1 " , " g e n d e r " : 2 , " i d " : 8 3 8 5 4 , " n a m e " : " d a v i d d a s t m a l c h i a n " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 3 9 5 , " c h a r a c t e r " : " r e p o r t e r " , " c r e d i t _ i d " : " 5 9 9 3 c e 0 a 9 2 5 1 4 1 5 4 2 b 0 0 d 5 9 b " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 3 , " n a m e " : " s o p h i a h i n s h e l w o o d " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 2 7 2 , " c h a r a c t e r " : " h e c k l e r " , " c r e d i t _ i d " : " 5 6 0 c 2 8 d b c 3 a 3 6 8 6 8 1 4 0 0 6 9 8 5 " , " g e n d e r " : 0 , " i d " : 1 3 1 3 0 9 3 , " n a m e " : " k e i t h k u p f e r e r " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 3 9 6 , " c h a r a c t e r " : " c o p h e c k l e r " , " c r e d i t _ i d " : " 5 9 9 3 c e 2 f c 3 a 3 6 8 7 e c 4 0 0 e 0 b 1 " , " g e n d e r " : 0 , " i d " : 1 6 7 8 5 6 6 , " n a m e " : " j o s e p h l u i s c a b a l l e r o " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 2 7 3 , " c h a r a c t e r " : " a c t i n g c o m m i s s i o n e r " , " c r e d i t _ i d " : " 5 6 0 c 2 9 0 2 c 3 a 3 6 8 6 8 2 4 0 0 5 e 2 9 " , " g e n d e r " : 2 , " i d " : 1 7 6 2 2 7 , " n a m e " : " r i c h a r d d i l l a n e " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 3 9 7 , " c h a r a c t e r " : " o f f i c e r a t i n t e r s e c t i o n " , " c r e d i t _ i d " : " 5 9 9 3 c e 9 8 c 3 a 3 6 8 7 e c 4 0 0 e 1 7 7 " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 4 , " n a m e " : " d a r y l s a t c h e r " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 3 9 8 , " c h a r a c t e r " : " c o n v o y l e a d e r " , " c r e d i t _ i d " : " 5 9 9 3 c e b 5 c 3 a 3 6 8 7 f 4 6 0 0 d 0 6 e " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 5 , " n a m e " : " c h r i s p e t s c h l e r " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 3 9 9 , " c h a r a c t e r " : " f a t t h u g " , " c r e d i t _ i d " : " 5 9 9 3 c e c 3 9 2 5 1 4 1 5 4 3 3 0 0 d 2 5 e " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 1 6 , " n a m e " : " a i d a n f e o r e " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 2 7 4 , " c h a r a c t e r " : " m u r p h y " , " c r e d i t _ i d " : " 5 6 0 c 2 a 1 2 c 3 a 3 6 8 6 8 0 b 0 0 6 2 8 b " , " g e n d e r " : 0 , " i d " : 1 1 2 8 8 5 4 , " n a m e " : " p h i l i p b u l c o c k " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 2 7 5 , " c h a r a c t e r " : " c o p w i t h f a t t h u g " , " c r e d i t _ i d " : " 5 6 0 c 2 a 3 f c 3 a 3 6 8 6 8 2 4 0 0 5 e 4 c " , " g e n d e r " : 2 , " i d " : 2 9 6 1 7 , " n a m e " : " p a u l b i r c h a r d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 4 0 0 , " c h a r a c t e r " : " m e d i c " , " c r e d i t _ i d " : " 5 9 9 3 c f 5 3 c 3 a 3 6 8 7 e f f 0 0 c 8 f 5 " , " g e n d e r " : 0 , " i d " : 1 7 8 1 7 3 9 , " n a m e " : " w a l t e r l e w i s " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 2 7 6 , " c h a r a c t e r " : " c o p a t 2 5 0 5 2 n d s t . " , " c r e d i t _ i d " : " 5 6 0 c 2 a 8 c 9 2 5 1 4 1 7 1 a 3 0 0 6 6 4 0 " , " g e n d e r " : 2 , " i d " : 2 6 6 6 9 , " n a m e " : " v i n c e n t r i o t t a " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 4 0 1 , " c h a r a c t e r " : " n u r s e " , " c r e d i t _ i d " : " 5 9 9 3 c f 7 8 c 3 a 3 6 8 7 e c 4 0 0 e 3 0 0 " , " g e n d e r " : 0 , " i d " : 1 6 3 1 7 0 7 , " n a m e " : " n a n c y c r a n e " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 2 7 7 , " c h a r a c t e r " : " p o l k " , " c r e d i t _ i d " : " 5 6 0 c 2 a d 6 c 3 a 3 6 8 6 8 1 f 0 0 5 c 1 4 " , " g e n d e r " : 2 , " i d " : 1 4 3 3 2 8 , " n a m e " : " k . t o d d f r e e m a n " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 2 7 8 , " c h a r a c t e r " : " b e r g " , " c r e d i t _ i d " : " 5 6 0 c 2 b 4 d c 3 a 3 6 8 6 8 2 4 0 0 5 e 6 e " , " g e n d e r " : 0 , " i d " : 1 4 6 4 8 5 4 , " n a m e " : " m a t t s h a l l e n b e r g e r " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 4 0 4 , " c h a r a c t e r " : " c o p a t h o s p i t a l " , " c r e d i t _ i d " : " 5 9 9 3 d 0 a 4 9 2 5 1 4 1 5 4 3 3 0 0 d 5 6 e " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 2 3 , " n a m e " : " m i c h a e l a n d r e w g o r m a n " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 4 0 2 , " c h a r a c t e r " : " b a r t e n d e r " , " c r e d i t _ i d " : " 5 9 9 3 d 0 2 b c 3 a 3 6 8 7 f 4 6 0 0 d 2 b 8 " , " g e n d e r " : 0 , " i d " : 1 8 7 0 6 2 0 , " n a m e " : " l a n n y l u t z " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 4 0 3 , " c h a r a c t e r " : " c i v i l i a n " , " c r e d i t _ i d " : " 5 9 9 3 d 0 3 e 9 2 5 1 4 1 5 4 2 3 0 0 c b 8 a " , " g e n d e r " : 2 , " i d " : 1 6 2 4 9 1 0 , " n a m e " : " p e t e r d e f a r i a " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 2 7 9 , " c h a r a c t e r " : " f i r s t m a t e " , " c r e d i t _ i d " : " 5 6 0 c 2 b a 4 c 3 a 3 6 8 6 8 1 0 0 0 6 6 b 9 " , " g e n d e r " : 2 , " i d " : 7 8 0 4 7 , " n a m e " : " m a t t r i p p y " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 2 8 0 , " c h a r a c t e r " : " p r i s o n f e r r y p i l o t " , " c r e d i t _ i d " : " 5 6 0 c 2 b c 6 c 3 a 3 6 8 6 8 0 b 0 0 6 2 b 1 " , " g e n d e r " : 2 , " i d " : 4 7 5 2 5 , " n a m e " : " a n d r e w b i c k n e l l " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 2 8 1 , " c h a r a c t e r " : " g u a r d c o m m a n d e r " , " c r e d i t _ i d " : " 5 6 0 c 2 b e 1 c 3 a 3 6 8 6 8 1 0 0 0 6 6 b f " , " g e n d e r " : 0 , " i d " : 1 2 3 8 4 6 1 , " n a m e " : " a r i y o n b a k a 

In [193]:
movie_index = new_df[new_df['title']=='Batman Begins'].index[0]

distances = similarity[movie_index]

sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[:10]

[(119, np.float64(1.0)),
 (110, np.float64(0.17541160386140586)),
 (1476, np.float64(0.15450786078738143)),
 (492, np.float64(0.14824986333222026)),
 (298, np.float64(0.14484136487558028)),
 (78, np.float64(0.1386750490563073)),
 (214, np.float64(0.1386750490563073)),
 (244, np.float64(0.1345345587992625)),
 (728, np.float64(0.1345345587992625)),
 (1012, np.float64(0.1345345587992625))]

In [195]:
new_df.iloc[1214].title

'Escape from New York'

In [196]:
import pickle

In [198]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [199]:
import os

print(os.getcwd())
print(os.path.exists("similarity.pkl"))
print(os.path.exists("movie_dict.pkl"))

C:\Users\HP
True
False

In [200]:
import pickle

pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [201]:
import os

print(os.getcwd())

C:\Users\HP